### ISSUE TITLE
no matches for kind "SparkApplication" when deploying job.

### ISSUE THREAD

**Issue by pkill-git** [GoogleCloudPlatform/spark-on-k8s-operator#1001]
Seems i'm missing a custom resource definition

Installing : 

```
kubectl create namespace spark-operator
kubectl create namespace spark-apps
```

Installed via HELM
`helm install operator incubator/sparkoperator --namespace spark-operator --set sparkJobNamespace=spark-apps`

```
NAME: operator
LAST DEPLOYED: Wed Aug 19 09:55:38 2020
NAMESPACE: spark-operator
STATUS: deployed
REVISION: 1
TEST SUITE: None
```
Get some info : 
```
helm list --all-namespaces
NAME            NAMESPACE       REVISION        UPDATED                                         STATUS          CHART                   APP VERSION
operator        spark-operator  1               2020-08-19 09:55:38.026973434 +0200 CEST        deployed        sparkoperator-0.8.2     v1beta2-1.2.0-3.0.0
```
Pods
```
kubectl get po -n spark-operator
NAME                                       READY   STATUS      RESTARTS   AGE
operator-sparkoperator-79c7c86999-fck42    1/1     Running     0          31s
operator-sparkoperator-crd-cleanup-j68qg   0/2     Completed   0          31s
```
Just a test file to reflect the error, shouldnt do anything,

```

apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-pi
  namespace: spark-apps
spec:
  type: Python
  pythonVersion: "2"
  mode: cluster
  image: "gcr.io/spark-operator/spark-py:v3.0.0"
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  sparkVersion: "3.0.0"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.0.0
```

And it errors on a 

`error: unable to recognize "python.yaml": no matches for kind "SparkApplication" in version "sparkoperator.k8s.io/v1beta2"`

Am i missing something here?

Thanks in advance.
