### ISSUE TITLE
Tolerations not applied to pods

### ISSUE THREAD

**Issue by sepulworld** [GoogleCloudPlatform/spark-on-k8s-operator#1006]
K8s version: 1.17
spark-operator: v1beta2-1.2.0-3.0.0

example adding a Toleration and NodeSelector:
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi-example
  namespace: spark-jobs
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v3.0.0"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.0.0.jar"
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  tolerations:
  - key: node-restriction.kubernetes.io/workloads
    operator: "Equal"
    value: "spark"
    effect: "NoSchedule"
  nodeSelector:
    node.kubernetes.io/instancegroup: spark
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: sparkoperator-spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.0.0
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
```

NodeSelector works, but the pod is not provisioned with tolerations requested in spec.

Only the default tolerations show up.
