### ISSUE TITLE
Not able to set spark configuration via .spec.sparkConf

### ISSUE THREAD

**Issue by suchitgupta01** [GoogleCloudPlatform/spark-on-k8s-operator#1036]
Hi Team,

I am exploring the Spark-Operator and was trying to set spark properties by .spec.sparkConf. However after trying hard, the changes are not getting reflected.

My yaml file:

```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: ScheduledSparkApplication
metadata:
   name: test_batch_job`
   namespace: default
spec:
  schedule: "@every 2m"
  concurrencyPolicy: Forbid
  successfulRunHistoryLimit: 1
  failedRunHistoryLimit: 3
  sparkConf:
    "spark.app.name": "test_batch"
    "spark.eventLog.enabled": "true"
    "spark.scheduler.mode": "FAIR"
  template:
    type: Scala
    mode: cluster
    image: "test/batch:latest"
    imagePullPolicy: Never
    mainClass: com.explore.BatchJob
    mainApplicationFile: "local:///app/target/scala-2.12/explore-assembly-0.1.jar"
    sparkVersion: "3.0.0"
    restartPolicy:
      type: Never
    driver:
      cores: 1
      coreLimit: "1200m"
      memory: "1024m"
      labels:
        version: 3.0.0
      serviceAccount: spark
    executor:
      cores: 2
      instances: 2
      memory: "1024m"
      labels:
        version: 3.0.0
```

My Scala code for getting session 
`
SparkSession
      .builder
      .appName("test_batch")
      .getOrCreate()
`

Dockerfile for building image

```
ARG SPARK_IMAGE=gcr.io/spark-operator/spark:v3.0.0
FROM ${SPARK_IMAGE}

ENV SBT_VERSION 1.3.13

USER root

RUN apt-get -y update && apt-get install -y curl

USER ${spark_uid}

WORKDIR /app/

RUN curl -fsL https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.tgz | tar xfz - -C /usr/local
ENV PATH /usr/local/sbt/bin:${PATH}

ADD build.sbt /app/
ADD project/plugins.sbt /app/project/
ADD project/build.properties /app/project/
ADD src/. /app/src/

RUN sbt update
RUN sbt clean assembly

ENTRYPOINT ["/opt/entrypoint.sh"]
```

Issue: The job is running, however spark properties like "spark.scheduler.mode" are not getting set. They are taking the default value.

I need help to understand how I can override the default configurations.

Spark: 3.0.0
Scala: 2.12
