### ISSUE TITLE
volumeMounts spec seems to be incorrect

### ISSUE THREAD

**Issue by ssiegel95** [GoogleCloudPlatform/spark-on-k8s-operator#1042]
[The user guide](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md)

shows, for example:

```yaml
 driver:
    volumeMounts:
      - name: spark-work
        mountPath: /mnt/spark/work
```

Shouldn't it be:

```yaml
 driver:
    volumeMounts:
      - mountPath: /mnt/spark/work
        name: spark-work
```

instead?
