### ISSUE TITLE
Support Prometheus PodMonitor Deployment

### ISSUE THREAD

**Issue by ordukhanian** [GoogleCloudPlatform/spark-on-k8s-operator#1106]
Hello, 
Could you please support Prometheus PodMonitor configuration and deployment for Spark Operator?
Currently the Spark GCP Operator exposes metrics endpoint, but there is no ability to configure Prometheus integration.

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spark-operator-gcp-monitor
  labels:
    <pod monitor labels>
spec:
  podMetricsEndpoints:
    - interval: 5s
      port: metrics
      path: /metrics
      scheme: http
  jobLabel: spark-operator-gcp-monitor
  namespaceSelector:
    matchNames:
      - spark-operator-gcp
  selector:
    matchLabels:
      app.kubernetes.io/name: sparkoperator
```
