### ISSUE TITLE
I can't see the batch latency metrics when using the prometheus image

### ISSUE THREAD

**Issue by joanjiao2016** [GoogleCloudPlatform/spark-on-k8s-operator#1121]
I have a sparkstreaming application, my Dockerfile is as follows:
```
FROM gcr.io/spark-operator/spark:v3.0.0-gcs-prometheus
USER ${spark_uid}
RUN mkdir -p /opt/spark/jars
COPY Spark.jar /opt/spark/jars

```

and the sparkapplication yaml is as follows:
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: streaming
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "${dockerstoreIp}/streaming:v1.0_metrics"
  imagePullPolicy: IfNotPresent
  mainClass: SparkConsumer
  mainApplicationFile: "local:///opt/spark/jars/Spark.jar"
  arguments:
    - "test"
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    hostNetwork: true
    labels:
      version: 3.0.0
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 5
    memory: "512m"
    hostNetwork: true
    labels:
      version: 3.0.0
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/prometheus/jmx_prometheus_javaagent-0.11.0.jar"
      port: 8090

```

My application was running well after started， but I couldn't find the metrics of streaming batch latency in the url: http://${driverportIp}:8090/metrics 

Can anyone help me？Thanks a lot！
