### ISSUE TITLE
nodeSelector does not work

### ISSUE THREAD

**Issue by thomaslee9595** [GoogleCloudPlatform/spark-on-k8s-operator#1211]
I have the following yaml file. I would like the driver run on a node with label "type" has value of "spark".

Doesn't seem to work. The only time I was able to get this working is by specifying nodeSelector at the SparkApplicationSpec level, not at the driver or executor level. 

Any ideas on this? 
```
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: job1
  namespace: spark-operator
spec:
  driver:
    coreLimit: 1200m
    cores: 1
    memory: 512m
    nodeSelector:
      type: spark2
    serviceAccount: spark
  executor:
    cores: 1
    instances: 3
    memory: 512m
  image: 'gcr.io/spark-operator/spark-py:v3.0.0'
  imagePullPolicy: Always
  mainApplicationFile: 'local:///opt/spark/examples/src/main/python/pi.py'
  mode: cluster
  pythonVersion: '2'
  restartPolicy:
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
    type: OnFailure
  sparkVersion: 3.0.0
  type: Python
```

**Comment by freemanlutsk** [comment]
@thomaslee9595 try to use the following version `tag: "v1beta2-1.2.1-3.0.0"`

**Comment by freemanlutsk** [comment]
@thomaslee9595  Do you mean something like that ?
```
      apiVersion: "sparkoperator.k8s.io/v1beta2"
      kind: SparkApplication
      metadata:
        namespace: "spark"
        name: "{{ SPARK_APP }}"
      spec:
        type: Scala
        mode: cluster
        image: "xxx"
        imagePullPolicy: Always
        nodeSelector:
          spark-node: "yes"
        mainClass: "xxx"
        mainApplicationFile: "xxx"
        sparkConf:
          spark.delta.logStore.class: "org.apache.spark.sql.delta.storage.S3SingleDriverLogStore"
          spark.kafka.brokers: "xxx"
          spark.dc: "xxx"
          spark.ui.prometheus.enabled: "true"
          spark.executor.processTreeMetrics.enabled: "true"
        hadoopConf:
          fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
          fs.s3a.access.key: "xxx"
          fs.s3a.secret.key: "xxx"
        sparkVersion: "3.0.0"
        restartPolicy:
          type: Always
          onFailureRetryInterval: 10
          onSubmissionFailureRetryInterval: 30
        driver:
          cores: 1
          memory: "8g"
          serviceAccount: spark
        executor:
          cores: 2
          coreRequest: "200m"
          coreLimit: "500m"
          instances: 5
          memory: "8g"
        monitoring:
          exposeDriverMetrics: true
          exposeExecutorMetrics: true
          prometheus:
            jmxExporterJar: "/prometheus/jmx_prometheus_javaagent-0.11.0.jar"
            port: 8090
```
