### ISSUE TITLE
servicemonitor support for sparkapplication & scheduledsparkapplication

### ISSUE THREAD

**Issue by suvashishtha** [GoogleCloudPlatform/spark-on-k8s-operator#1221]
i want to export metrics to prometheus from sparkapplication & scheduledsparkapplication using servicemonitor. Is it possible ?
Operator version is: 1.0.5

**Comment by suvashishtha** [comment]
can just add a new service and servicemonitor to the job and it works fine

**Comment by vishal98** [comment]
can you explain it bit more?

**Comment by suvashishtha** [comment]
added a new service  to get all the metrics from driver and executor pods & then defined a new servicemonitor to get those metrics to prometheus.

service definition:

```
apiVersion: v1
kind: Service
name: metrics-svc
labels:
  monitoring: spark-monitoring
spec:
  ports:
  - name: metrics
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: spark-job
    release: spark-job
  type: ClusterIP
```

servicemonitor
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
name: spark-metrics-collector
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: metrics
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      monitoring: spark-monitoring
```
