### ISSUE TITLE
Spark can't createfiles under hostPath mount points

### ISSUE THREAD

**Issue by leandro-rouberte** [GoogleCloudPlatform/spark-on-k8s-operator#1228]
Hi, everyone.

I'm trying to use the hostPath feature in k8s, but without success. 
I'm running k8s using docker-desktop for macos version 3.3.0.
My spark-operator helm chart version is 1.0.8 and spark-operator image is using the latest version.

This is what I'm doing in my sparkApplication yaml:
```yaml
volumes:
    - name: "spark-local-dir-1"
      hostPath:
        path: "/tmp/spark-local-dir"
 .....
 executor:
    volumeMounts:
      - name: "spark-local-dir-1"
        mountPath: "/tmp/spark-local-dir"
    cores: 1
    coreLimit: "1000m"
```
When I do that the executor keeps crashing with the following error
```
21/04/15 21:46:29 ERROR DiskBlockManager: Failed to create local dir in /mnt/spark-data. Ignoring this directory.                                                                                                                                                            │
│ java.io.IOException: Failed to create a temp directory (under /mnt/spark-data) after 10 attempts!                                                                                                                                                                            │
│     at org.apache.spark.util.Utils$.createDirectory(Utils.scala:304)                                                                                                                                                                                                         │
│     at org.apache.spark.storage.DiskBlockManager.$anonfun$createLocalDirs$1(DiskBlockManager.scala:144)                                                                                                                                                                      │............
│ 21/04/15 21:46:29 ERROR DiskBlockManager: Failed to create any local dir.
```

It seems like a privilege issue, but I wasn't able to figure out what privilege was missing. 

Also tested with a simple pod and hostPath is working fine. Here's the manifest of the pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  volumes:
    - name: test 
      hostPath:
        path: "/tmp/spark-local-dir"
  containers:
    - image: nginx
      name: test
      volumeMounts: 
       - mountPath: /mnt/test
         name: test
```

From inside the pod: 
```bash
root@test:/mnt/test# echo test > test.txt
root@test:/mnt/test# ls
test.txt
```

From inside docker-desktop linux vm:
```bash
root@2d916458ffac:/tmp/spark-local-dir# ls
test.txt
```
