### ISSUE TITLE
Openshift : Unable to run spark application on enabling mutating webhook

### ISSUE THREAD

**Issue by gauravbh1** [GoogleCloudPlatform/spark-on-k8s-operator#1232]
Openshift version 4.6.16 and 4.3.40
Installed spark operator using helm chart : `helm install spark-operator spark-operator/spark-operator --namespace spark-operator --create-namespace --set image.tag=latest --set webhook.enable=true` 
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/17174201/115412826-51c66680-a212-11eb-9b0a-bb512f775c46.png">

Installation goes through smoothly.
Deployed a custom spark application using the following manifest. The manifest uses volume mounts. On deploying the app, the driver fails. Removing the volume mount specs from the manifest yaml and redeploying, the app runs successfully

**Manifest yml**
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-streaming-producer-python
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "quay.io/gauravbh1/spark-consumer:latest"
  imagePullPolicy: Always
  mainApplicationFile: local:///app/src/stream.py
  sparkVersion: "3.0.0"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 5
    onFailureRetryInterval: 11
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  volumes:
    - name: spark-work
      emptyDir: {}
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "2048m"
    labels:
      version: 3.0.0
    volumeMounts:
      - name: spark-work
        mountPath: /app/src
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "1024m"
    labels:
      version: 3.0.0
```
App driver log has the following logs

> ++ id -u
+ myuid=0
++ id -g
+ mygid=0
+ set +e
++ getent passwd 0
+ uidentry=root:x:0:0:root:/root:/bin/bash
+ set -e
+ '[' -z root:x:0:0:root:/root:/bin/bash ']'
+ SPARK_CLASSPATH=':/opt/spark/jars/*'
+ env
+ grep SPARK_JAVA_OPT_
+ sort -t_ -k4 -n
+ sed 's/[^=]*=\(.*\)/\1/g'
+ readarray -t SPARK_EXECUTOR_JAVA_OPTS
+ '[' -n '' ']'
+ '[' -z ']'
+ '[' -z ']'
+ '[' -n '' ']'
+ '[' -z ']'
+ '[' -z x ']'
+ SPARK_CLASSPATH='/opt/spark/conf::/opt/spark/jars/*'
+ case "$1" in
+ shift 1
+ CMD=("$SPARK_HOME/bin/spark-submit" --conf "spark.driver.bindAddress=$SPARK_DRIVER_BIND_ADDRESS" --deploy-mode client "$@")
+ exec /usr/bin/tini -s -- /opt/spark/bin/spark-submit --conf spark.driver.bindAddress=10.254.0.109 --deploy-mode client --properties-file /opt/spark/conf/spark.properties --class org.apache.spark.deploy.PythonRunner local:///app/src/stream.py
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/spark/jars/spark-unsafe_2.12-3.1.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
21/04/20 13:49:49 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
python3: can't open file '/app/src/stream.py': [Errno 2] No such file or directory
log4j:WARN No appenders could be found for logger (org.apache.spark.util.ShutdownHookManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Spark-operator pod logs (partial logs pasted)

>   I0420 13:44:47.666663      11 event.go:274] Event(v1.ObjectReference{Kind:"SparkApplication", Namespace:"default", Name:"spark-streaming-producer-python", UID:"ebce0b97-493c-45c1-ad0c-e764edd28cb3", APIVersion:"sparkoperator.k8s.io/v1beta2", ResourceVersion:"4343067", FieldPath:""}): type: 'Normal' reason: 'SparkDriverRunning' Driver spark-streaming-producer-python-driver is running
I0420 13:44:47.697604      11 controller.go:218] SparkApplication default/spark-streaming-producer-python was updated, enqueueing it
I0420 13:44:47.698031      11 metrics.go:112] Incrementing spark_app_running_count with labels map[app_type:Unknown]
I0420 13:44:47.698084      11 controller.go:265] Ending processing key: "default/spark-streaming-producer-python"
I0420 13:44:47.698130      11 controller.go:258] Starting processing key: "default/spark-streaming-producer-python"
I0420 13:44:47.698540      11 controller.go:265] Ending processing key: "default/spark-streaming-producer-python"
I0420 13:44:52.802800      11 spark_pod_eventhandler.go:58] Pod spark-streaming-producer-python-driver updated in namespace default.
I0420 13:44:52.802861      11 spark_pod_eventhandler.go:95] Enqueuing SparkApplication default/spark-streaming-producer-python for app update processing.
I0420 13:44:52.802936      11 controller.go:258] Starting processing key: "default/spark-streaming-producer-python"
I0420 13:44:52.803252      11 controller.go:773] Update the status of SparkApplication default/spark-streaming-producer-python from:
{
  "sparkApplicationId": "spark-82c629ad1cb84f45b40634cb1441b145",
  "submissionID": "e1ece93a-c97b-417a-8ac7-740742142ec8",
  "lastSubmissionAttemptTime": "2021-04-20T13:44:43Z",
  "terminationTime": null,
  "driverInfo": {
    "webUIServiceName": "spark-streaming-producer-python-ui-svc",
    "webUIPort": 4040,
    "webUIAddress": "172.30.150.74:4040",
    "podName": "spark-streaming-producer-python-driver"
  },
  "applicationState": {
    "state": "RUNNING"
  },
  "executionAttempts": 2,
  "submissionAttempts": 1
}
to:
{
  "sparkApplicationId": "spark-82c629ad1cb84f45b40634cb1441b145",
  "submissionID": "e1ece93a-c97b-417a-8ac7-740742142ec8",
  "lastSubmissionAttemptTime": "2021-04-20T13:44:43Z",
  "terminationTime": "2021-04-20T13:44:52Z",
  "driverInfo": {
    "webUIServiceName": "spark-streaming-producer-python-ui-svc",
    "webUIPort": 4040,
    "webUIAddress": "172.30.150.74:4040",
    "podName": "spark-streaming-producer-python-driver"
  },
  "applicationState": {
    "state": "FAILING",
    "errorMessage": "driver container failed with ExitCode: 2, Reason: Error"
  },
  "executionAttempts": 2,
  "submissionAttempts": 1
}
I0420 13:44:52.803855      11 event.go:274] Event(v1.ObjectReference{Kind:"SparkApplication", Namespace:"default", Name:"spark-streaming-producer-python", UID:"ebce0b97-493c-45c1-ad0c-e764edd28cb3", APIVersion:"sparkoperator.k8s.io/v1beta2", ResourceVersion:"4343089", FieldPath:""}): type: 'Warning' reason: 'SparkDriverFailed' Driver spark-streaming-producer-python-driver failed
I0420 13:44:52.854076      11 metrics.go:125] Decrementing spark_app_running_count with labels map[app_type:Unknown] metricVal to 0
I0420 13:44:52.854142      11 controller.go:265] Ending processing key: "default/spark-streaming-producer-python"
I0420 13:44:52.855704      11 controller.go:218] SparkApplication default/spark-streaming-producer-python was updated, enqueueing it
I0420 13:44:52.855842      11 controller.go:258] Starting processing key: "default/spark-streaming-producer-python"
I0420 13:44:52.856100      11 controller.go:265] Ending processing key: "default/spark-streaming-producer-python"
I0420 13:44:54.330624      11 webhook.go:246] Serving admission request
I0420 13:44:54.331481      11 webhook.go:540] Pod  in namespace openshift-operator-lifecycle-manager is not subject to mutation

 Note : I don't see the tls related errors as described in some other issues. 
Is there an alternative way of installing the operator with mutating webhooks? This issue prevents us from using volume mounts in the app.
