### ISSUE TITLE
metrics.properties can not mount as a configmap

### ISSUE THREAD

**Issue by joanjiao2016** [GoogleCloudPlatform/spark-on-k8s-operator#1238]
Hi all，
   I wanted to mount metrics.propertis as a configmap, but it didn't work ，can anyone help ？ Thanks a lot！

```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "pi-metrics"
  namespace: sparkop
spec:
  type: Scala
  mode: cluster
  image: "xxx/sparkop/spark:metricstest"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.0.0.jar"
  arguments:
    - "300000"
  sparkConf:
    "spark.metrics.conf" : "/etc/metrics.properties"
  sparkVersion: "3.0.0"
  volumes:
    - name: metrics
      configMap:
        name: config-metrics
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "2000m"
    memory: "2048m"
    labels:
      version: 3.0.0
    serviceAccount: sparkop
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
      - name: metrics
        mountPath: "/etc"
  executor:
    cores: 2
    instances: 3
    coreLimit: "3000m"
    memory: "2048m"
    labels:
      version: 3.0.0
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
      - name: metrics
        mountPath: "/etc"

```
