### ISSUE TITLE
Support workload identity in GKE

### ISSUE THREAD

**Issue by danielhstahl** [GoogleCloudPlatform/spark-on-k8s-operator#1241]
[Workload identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) is the preferred method to consume GCP resources from GKE.  However, it does not seem to work with this operator.  Is there any plans to support workload identity for GKE applications?

**Comment by liyinan926** [comment]
Can you be more specific on this? Are you referring to GCP resource management from within the operator pod or the Spark driver/executor pods? If it's the latter, it should work as long as you use a k8s service account for the driver/executor pods that is bound to a GCP service account through Workload Identity.

**Comment by jherrmannNetfonds** [comment]
Hi, my issue on this topic is that the operator pod (not driver or executor) should load the `mainApplicationFile` from google cloud storage bucket and also dependencies. I am installing the chart in an GKE autopilot private cluster.
First I had to build the operator image from an image with gcs support. This is supported by the chart.
Second to access the storage I want to use a special service account which I made available to the image by mounting the secret to the operator. For this to work the only way I found is modifying the chart. I added the following part to `charts\spark-operator-chart\templates\deployment.yaml`
```yaml
        volumeMounts:
          - name: webhook-certs
            mountPath: /etc/webhook-certs
          - name: google-cloud-key
            mountPath: /var/secrets/google
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
      volumes:
        - name: webhook-certs
          secret:
            secretName: {{ include "spark-operator.fullname" . }}-webhook-certs
        - name: google-cloud-key
          secret:
            secretName: netfonds-dwh-sa
```
Sidenote: on the driver/executor pods I am using the option `secretType: GCPServiceAccount` to access GCP ressources.

I now found this tutorial which might actually make the change to the chart obsolete by using IAM policy binding: 
https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to
