### ISSUE TITLE
Fix spark rbac permissions

### ISSUE THREAD

**Issue by josecsotomorales** [GoogleCloudPlatform/spark-on-k8s-operator#1270]
Hey team! tried to create a PR for this but don't have permissions, the spark rbac manifests are missing the configmaps resources in the rules:
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/ca473c9a35b5a8d9bf4189b323e154b52f8fd4f1/manifest/spark-rbac.yaml#L28

missing rule:
```
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
```

Updated role manifest:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: demo
  name: spark-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["*"]
```
