### ISSUE TITLE
How to set log4j.properties in SparkApplication? 

### ISSUE THREAD

**Issue by LeonardAukea** [GoogleCloudPlatform/spark-on-k8s-operator#1278]
What is the suggested way to set custom log4j.properties in the `SparkApplication`? 

I've been trying to get `DEBUG` logs out of driver in the hope of gaining more insight in the issue by setting: 

```yaml 
spec:
  sparkConfigMap: log4j-props
```
as described in the documentation and generating the a cm from file using: 

```yaml
configMapGenerator:
  - files:
    - config/log4j.properties
    name: log4j-props  
generatorOptions:
 disableNameSuffixHash: true
```

But it does not seem to be recognized: 

```
**Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties**
```

log4j.properties
```
log4j.rootCategory=DEBUG, console
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.target=System.err
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n
# Set the default spark-shell/spark-sql log level to WARN. When running the
# spark-shell/spark-sql, the log level for these classes is used to overwrite
# the root logger's log level, so that the user can have different defaults
# for the shell and regular Spark apps.
log4j.logger.org.apache.spark.repl.Main=DEBUG
log4j.logger.org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver=WARN
# Settings to quiet third party logs that are too verbose
log4j.logger.org.sparkproject.jetty=WARN
log4j.logger.org.sparkproject.jetty.util.component.AbstractLifeCycle=ERROR
log4j.logger.org.apache.spark.repl.SparkIMain$exprTyper=INFO
log4j.logger.org.apache.spark.repl.SparkILoop$SparkILoopInterpreter=INFO
log4j.logger.org.apache.parquet=ERROR
log4j.logger.parquet=ERROR
# SPARK-9183: Settings to avoid annoying messages when looking up nonexistent UDFs in SparkSQL with Hive support
log4j.logger.org.apache.hadoop.hive.metastore.RetryingHMSHandler=FATAL
log4j.logger.org.apache.hadoop.hive.ql.exec.FunctionRegistry=ERROR
# For deploying Spark ThriftServer
# SPARK-34128：Suppress undesirable TTransportException warnings involved in THRIFT-4805
log4j.appender.console.filter.1=org.apache.log4j.varia.StringMatchFilter
log4j.appender.console.filter.1.StringToMatch=Thrift error occurred during processing of message
log4j.appender.console.filter.1.AcceptOnMatch=false
```

**Comment by LeonardAukea** [comment]
I found the answer: 

```yaml
javaOptions: -Dlog4j.configuration=/path/to/log4j.properties  
```

In addition to this it might be useful to know that you can set DEBUG logs for the spark-submit that is being executed by the operator by mounting the log4j.properties as a cm in the Deployment manifest: 

```yaml 
        volumeMounts:
          - mountPath: /opt/spark/conf
            name: log4j-props           
      volumes:
        - configMap:
            name: log4j-props
          name: log4j-props
```
