### ISSUE TITLE
Support for volumempounts in initContianer

### ISSUE THREAD

**Issue by varunshaji** [GoogleCloudPlatform/spark-on-k8s-operator#1320]
```
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: 
https://172.20.0.1/api/v1/namespaces/spark-cluster/pods. Message: 
Pod "pyspark-pi-driver" is invalid: [spec.initContainers[0].volumeMounts[0].name: Not found: 
"script", spec.initContainers[0].volumeMounts[1].name: Not found: "git-secret"]. Received status: 
Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.initContainers[0].volumeMounts[0].name, 
  ssage=Not found: "script", reason=FieldValueNotFound, additionalProperties={}), 
StatusCause(field=spec.initContainers[0].volumeMounts[1].name, message=Not found: "git-secret", 
  reason=FieldValueNotFound, additionalProperties={})], group=null, kind=Pod, name=pyspark-pi-driver,
   retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Pod "pyspark-pi-driver" 
is invalid: [spec.initContainers[0].volumeMounts[0].name: Not found: "script", spec.initContainers[0].volumeMounts[1].name: 
Not found: "git-secret"], metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null,
 selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
```

This is useful cass like using git-syn as part of spark operator

**Comment by gauravbh1** [comment]
It would help if you can show your deployment yaml. However, looking at your error, it seems you are defining a secret as volume and then trying to mount the same as a volume mount inside the initContainer.

The scenario s supported but not very well documented. First you have to mount the volume on the driver and /or executor and subsequently on the initContainer. 
One example below.
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
version : 1.0
metadata:
  name: spark-pi
  namespace: testns
spec:
  type: Scala
  mode: cluster
  image: "quay.io/gauravbh1/analytics-sparkservice"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.1.1.jar"
  sparkVersion: "3.1.1"
  volumes:
    - name: empty-volume
      emptyDir: { }
    - name: git-secret
      secret:
        secretName: git-secret
  restartPolicy:
    type: OnFailure
    onFailureRetries: 5
    onFailureRetryInterval: 11
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    memory: "700m"
    volumeMounts:
      - name: git-secret
        mountPath: "/secret"
      - name: empty-volume
        mountPath: "/demo"
    initContainers:
      - name: installexec
        image: quay.io/jitesoft/alpine
        command: [ 'sh', '-c', 'cp -R /secret/*.* /demo && ls /demo' ]
        volumeMounts:
          - name: git-secret
            mountPath: "/secret"
          - name: empty-volume
            mountPath: "/demo"
    labels:
      version: 3.1.1
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "700m"
    volumeMounts:
      - name: git-secret
        mountPath: "/secret"
      - name: empty-volume
        mountPath: "/demo"
    initContainers:
      - name: installexec
        image: quay.io/jitesoft/alpine
        command: [ 'sh', '-c', 'cp -R /secret/*.* /demo && ls /demo' ]
        volumeMounts:
          - name: git-secret
            mountPath: "/secret"
          - name: empty-volume
            mountPath: "/demo"
    labels:
      version: 3.1.1

```
