### ISSUE TITLE
Spark executors won't start

### ISSUE THREAD

**Issue by yuchaoran2011** [GoogleCloudPlatform/spark-on-k8s-operator#133]
I have a docker image for a Spark 2.3 job that I could run successfully on Kubernetes using spark-submit. But when I started the job using the operator, the only things that got started were the driver pod and the UI svc, no Spark executors were launched. I didn't see any error in the sparkoperator pod and my app's driver pod. Anyone know what might be causing this issue? Btw, running the example spark-pi job using the operator works fine (executors got started etc).

**Comment by yuchaoran2011** [comment]
I'd like to add a "Help wanted" label to this issue as recommended in  contributing guidelines, but apparently I don't have the permission to do that. I'd appreciate it if someone can do that.

**Comment by yuchaoran2011** [comment]
Thanks for the reply. No, the executor pods were not created. Only the driver pod was there and running. I don’t remember seeing resource related messages in the logs. And running the app with spark-submit in the same cluster environment worked. I’ll double check later today to make sure this is the case.

**Comment by yuchaoran2011** [comment]
Ok so I've verified it's not a resource issue. Here's the Spark-submit command I used that worked:

```bash
bin/spark-submit \
       --master k8s://http://10.0.6.184:9000 \
       --deploy-mode cluster \
       --files http://api.hdfs.marathon.l4lb.thisdcos.directory/v1/endpoints/hdfs-site.xml,http://api.hdfs.marathon.l4lb.thisdcos.directory/v1/endpoints/core-site.xml \
       --name killrweather \
       --class com.lightbend.killrweather.app.KillrWeather \
       --conf spark.executor.instances=3 \
       --conf spark.kubernetes.mountDependencies.filesDownloadDir=/etc/hadoop/conf \
       --conf 'spark.driver.extraJavaOptions=-Dconfig.resource=cluster.conf' \
       --conf spark.kubernetes.container.image=lightbend/killrweather:2.3.0 \
       --conf spark.kubernetes.container.image.pullPolicy=Always \
       local:///opt/spark/jars/killrWeatherApp-assembly-1.1.0.jar
```

When submitted the same job using the following operator YAML, the executor pods are not created at all.

```yaml
apiVersion: sparkoperator.k8s.io/v1alpha1
kind: SparkApplication
metadata:
 name: kw
 namespace: default
spec:
 type: Scala
 mode: cluster
 image: lightbend/killrweather:2.3.0
 mainClass: com.lightbend.killrweather.app.KillrWeather
 mainApplicationFile: local:///opt/spark/jars/killrWeatherApp-assembly-1.1.0.jar
 sparkConf:
     "spark.kubernetes.mountDependencies.filesDownloadDir": /etc/hadoop/conf
     "spark.driver.extraJavaOptions": -Dconfig.resource=cluster.conf
 deps:
     files:
       - http://api.hdfs.marathon.l4lb.thisdcos.directory/v1/endpoints/hdfs-site.xml
       - http://api.hdfs.marathon.l4lb.thisdcos.directory/v1/endpoints/core-site.xml
 executor:
     cores: 1
     instances: 3
     memory: 512m
     labels:
      version: 2.3.0
 driver:
     cores: 1
     memory: 512m
     serviceAccount: spark
     labels:
      version: 2.3.0
````
