### ISSUE TITLE
CronJob(ScheduledSparkApplication) does not launch any pods 

### ISSUE THREAD

**Issue by dharmeshkakadia** [GoogleCloudPlatform/spark-on-k8s-operator#142]
I am able to run python spark applications without any issues, but when I add the ``schedule`` and change from ``SparkApplication`` to ``ScheduledSparkApplication`` (with other required changes) it fails to start any pods. It creates the service which fails with following and nothing happens. 

```
Error creating load balancer (will retry): error getting LB for service default/spark-my-wc-py-1525717818370411106-365697849-ui-svc: Service(default/spark-my-wc-py-1525717818370411106-365697849-ui-svc) - Loadbalancer not found
```

Env: 
I am running the 2.2 fork which has the python support. 

kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

Here is the deployment YAML for scheduledsparkapplication . 
```YAML
apiVersion: "sparkoperator.k8s.io/v1alpha1"
kind: ScheduledSparkApplication
metadata:
  name: pyspark-example
  namespace: default
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Replace
  runHistoryLimit: 3
  template:
    type: Python
    mode: cluster
    mainApplicationFile: "/code/pyspark-example.py"
    Arguments:
    - "wasb://sparkdkakadia@sparkdkakadia.blob.core.windows.net/episodes.avro"
    deps:
      jars:
        - "local:///opt/spark/examples/jars/spark-examples_2.11-2.2.0-k8s-0.5.0.jar" 
    sparkConf:
      "spark.hadoop.fs.azure.account.key.sparkdkakadia.blob.core.windows.net": "4gIguFMiymTI4BoHL2LsbIdEVjDYUZfcgj+/eUXWH9RzJPQAlQpUsT1+hAAsVJdlZd9fBQ+ctZV+I55A=="
    driver:
      cores: 0.1
      image: dharmeshkakadia/spark-py-example:latest
      coreLimit: "200m"
      memory: "1024m"
      labels:
        version: 2.2.0
      serviceAccount: spark
    executor:
      cores: 1
      instances: 2
      image: dharmeshkakadia/spark-executor-py:latest
      memory: "1024m"
      labels:
        version: 2.2.0
    restartPolicy: Never
```
