### ISSUE TITLE
Spark Driver and Executors cannot be configured with less than 1 core

### ISSUE THREAD

**Issue by sergialonsaco** [GoogleCloudPlatform/spark-on-k8s-operator#1458]
By documentation, spark driver task should be able to be configured with a number smaller than 1:
For example in https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#requesting-gpu-resources it says:
```
spec:
  driver:
    cores: 0.1
    coreLimit: "200m"
    memory: "512m"
    gpu:
      name: "amd.com/gpu"   # GPU resource name
      quantity: 1           # number of GPUs to request
    labels:
      version: 3.1.1
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    serviceAccount: spark
    gpu:
      name: "nvidia.com/gpu"
      quantity: 1
```

I'm trying to run a spark job with spark driver cores 0.25 and the next error appears:
```
spec.driver.cores: Invalid value: 0.25: spec.driver.cores in body should be greater than or equal to 1
```

So, how should we configure the driver/executors cores? Also looks a bit inconsistent that the cores should be configured with an integer value but the coreLimit and the memory with string values.
