### ISSUE TITLE
how to add many arguments in the yaml config?

### ISSUE THREAD

**Issue by yangqi766** [GoogleCloudPlatform/spark-on-k8s-operator#1541]
```
  mainClass: ai.autox.spark.WebTileGenerator
  sparkConf:
    spark.hadoop.fs.s3a.aws.credentials.provider: "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    spark.driver.extraClassPath: "local:///root/install/bin/*"
    spark.executor.extraClassPath: "local:///root/install/bin/*"
  mainApplicationFile: "local:///root/install/bin/WebTileGeneration-0.1.0-jar-with-dependencies.jar"
  arguments:
    - --input_path s3a://2022_05_24_00_31_48_developing
    - --output_path s3a://tms_tile/2022_05_24_00_31_48_developing_test3
    - --group_filter all
    - --num_driver_threads 128
    - --num_upload_partitions 8
    - --enable_annotation
```
I test the config above , but has the error :

exec /usr/sbin/tini -s -- /opt/spark/bin/spark-submit --conf spark.driver.bindAddress=172.16.176.165 --deploy-mode client --properties-file /opt/spark/conf/spark.properties --class  spark.WebTileGenerator local:///root/install/bin/WebTileGeneration-0.1.0-jar-with-dependencies.jar '--input_path s3a://maps/2022_05_24_00_31_48_developing' '--output_path s3a://tms_tile/2022_05_24_00_31_48_developing_test3' '--group_filter all' '--num_driver_threads 128' '--num_upload_partitions 8' --enable_annotation

Exception in thread "main" org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --input_path s3a://maps/2022_05_24_00_31_48_developing
	at org.apache.commons.cli.Parser.processOption(Parser.java:
