### ISSUE TITLE
Delete the failed Spark Application driver pods automatically

### ISSUE THREAD

**Issue by brshravan-tech** [GoogleCloudPlatform/spark-on-k8s-operator#1543]
Hi Team,

I noticed that in case of errors such as "expected secret is not found" etc, spark driver pods are failing with error "CreateContainerConfigError". But I see that these pods are not getting deleted automatically after sometime.
Can someone please help me with setting some timeout so that above failed pods are deleted automatically after sometime?

FYI, below is the scheduledsparkapplication yaml spec

```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: ScheduledSparkApplication
metadata:
  name: testname
  namespace: spark
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Allow
  timeToLiveSeconds: 900
  template:
    type: Python
    pythonVersion: "3"
    mode: cluster
    sparkVersion: "3.1.1"
    timeToLiveSeconds: 90
    failureRetries: 1
    retryInterval: 60
    restartPolicy:
      type: OnFailure
      onFailureRetries: 1
      onFailureRetryInterval: 10
      onSubmissionFailureRetries: 2
      onSubmissionFailureRetryInterval: 10
    driver:
      coreRequest: "500m"
      memory: "512m"
      ephemeral-storage: "512m"
      labels:
        version: 3.1.1
      serviceAccount: spark
    executor:
      coreRequest: "500m"
      instances: 1
      memory: "512m"
      ephemeral-storage: "512m"
      labels:
        version: 3.1.1
```

Thanks
