### ISSUE TITLE
spark-operator-rbac should only grant required roles

### ISSUE THREAD

**Issue by scotthew1** [GoogleCloudPlatform/spark-on-k8s-operator#162]
spark-operator-rbac.yaml currently grants ALL roles to the spark-operator service account.
```yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: sparkoperator
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
```
it should only be granted the roles it actually needs.
