### ISSUE TITLE
SparkApplication with volcano scheduler not working on OCP

### ISSUE THREAD

**Issue by disaster37** [GoogleCloudPlatform/spark-on-k8s-operator#1723]
Hi,

it seems SparkApplication not working with volcano sheduler on OCP.

I get the following error on SparkApplication Object

```
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://10.54.0.1/api/v1/namespaces/spark-hpd1/pods. Message: admission webhook "validatepod.volcano.sh" denied the request: failed to get PodGroup for pod <spark-hpd1/spark-test-driver>: podgroups.scheduling.volcano.sh "spark-spark-test-pg" not found. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=admission webhook "validatepod.volcano.sh" denied the request: failed to get PodGroup for pod <spark-hpd1/spark-test-driver>: podgroups.scheduling.volcano.sh "spark-spark-test-pg" not found, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=null, status=Failure, additionalProperties={}).
```

Same error on volcano-admission pod.

No logs on volcano-controller

I doesn't found whitch pod is supposed to create podGroup before create pod executor that run spark-submit.

It doesn't create any pod, no executor pod, no driver pod...

I follow the doc https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/volcano-integration.md

Spark-operator version: helm 1.1.27 It use image `ghcr.io/googlecloudplatform/spark-operator:v1beta2-1.3.8-3.1.1`
Volcano version: v1.7.0. It use image `volcanosh/vc-controller-manager:v1.7.0`

Add the spark applicatin:

```yaml
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-test
  namespace: spark-hpd1
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v3.1.1"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-v3.1.1.jar"
  sparkVersion: "3.1.1"
  batchScheduler: "volcano"   #Note: the batch scheduler name must be specified with `volcano`
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
  executor:
    cores: 1
    instances: 1
    memory: "512m"    
    labels:
      version: 3.1.1
```
