### ISSUE TITLE
`tolerations` and `affinity` rules not passing to Driver and Executor pods despite webhook enabled

### ISSUE THREAD

**Issue by JunaidChaudry** [GoogleCloudPlatform/spark-on-k8s-operator#1725]
I have webhook enabled in my spark-operator installation. However despite that, I am unable to use ANY properties on the driver and executor pods which require webhook, including [`tolerations`](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#using-tolerations), [`affinity`](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#using-pod-affinity), as well as `volumeMounts`. Can someone please look into it? 

I have also tried adding `namespaceSelector` to the webhook, and updating my namespace labels accordingly, however that doesn't help either.

### Spark Operator Helm Values
```yaml
image:
  pullPolicy: IfNotPresent
  repository: googlecloudplatform/spark-operator
webhook:
  enable: true
```
chart version: v1beta2-1.3.8-3.1.1

### Sample Spark Application
```yaml

apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: sample-app
  namespace: spark-operator
spec:
  nodeSelector:                                # works correctly
    worker-group: wg3
  volumes:                                       # doesn't work
    - name: configmap1
      configMap: 
        name: mytestcm
  sparkConf:
    "spark.kubernetes.local.dirs.tmpfs": "true"
    "spark.kubernetes.submission.connectionTimeout": "60000000"
    "spark.kubernetes.submission.requestTimeout": "60000000"
    "spark.kubernetes.driver.connectionTimeout": "60000000"
    "spark.kubernetes.driver.requestTimeout": "60000000"
  type: Python
  mode: cluster
  mainClass: org.apache.spark.deploy.PythonRunner
  pythonVersion: "3"
  imagePullSecrets:
    ["my-artifactory"]
  image: "<myrepourl>/infoblox/dnstools:latest"
  imagePullPolicy: Always
  mainApplicationFile: "local:///app/asdf.py"
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never

  dynamicAllocation:
    enabled: true
    initialExecutors: 1
    minExecutors: 1
    maxExecutors: 50
  driver:
    volumeMounts:                                       # doesn't work
      - name: configmap1
        mountPath: /mnt/config-maps
    tolerations:                                        # doesn't work
    - key: "stack"
      value: "monitoring"
      effect: "NoSchedule" 
    memory: "512m"    
    labels:
      version: 3.0.0
    # spark operator service account created in the namespace, along with the role binding
    serviceAccount: jct-de-trigger-manager-jct-workflow-spark-app
  executor:
    tolerations:                                        # doesn't work
    - key: "stack"
      value: "monitoring"
      effect: "NoSchedule" 
    labels:
      version: 3.0.0
```
