### ISSUE TITLE
IngressClass support

### ISSUE THREAD

**Issue by tomglaza** [GoogleCloudPlatform/spark-on-k8s-operator#1733]
Is it possible to set ingressClassName in an ingress object?

I have several ingresses in the cluster (including nginx only for spark) and I would like to be able to set the default ingress in the cluster, but then SparkUI stops working for me (due to using `nginx.ingress.kubernetes.io/rewrite-target`, which my default ingress does not understand).

I currently work around this problem by using `kyverno` and modifying each newly created ingress in namespace sparkjobs. However, would prefer to be able to set in spark-operator which ingressClass I want to use.

**Comment by fei819** [comment]
not sure why https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1610 was not merged. Anyone?

**Comment by SBatais** [comment]
I would like to know if ingressClassName has been really implemented

**Comment by DOUS3L** [comment]
i tried to define the ingress class using annotations and it works
```yaml
...
  sparkUIOptions:
    servicePort: 4040
    serviceType: NodePort
    ingressAnnotations:
      # for k8s to read
      kubernetes.io/ingress.class: nginx-internal
      # for operator to read, without this ingress resource would not spawn
      ingress.class: nginx-internal
...
```
