### ISSUE TITLE
Hi @joanjiao2016 ,

### ISSUE THREAD

**Issue by jiangjian0920** [GoogleCloudPlatform/spark-on-k8s-operator#1744]
Hi @joanjiao2016 ,

You can refer to below simple examples -

Example 1 -
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-kerberos
  namespace: default
spec:
  type: Python
  pythonVersion: "2"
  mode: cluster
  image: "gcr.io/spark-operator/spark-py:v3.0.0"
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never
  hadoopConfigMap: "<HADOOP_CONFIG_MAP_NAME>"
  kerberos:
    enabled: true
	kerberosPrincipal: "<PRINCIPAL>"
	keytabSecret: "<KEYTAB_SECRET>"
	keytabName: "<KEYTAB_FILE_NAME>"
	krb5ConfigMap: "<KRB5_CONFIG_MAP_NAME>"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.0.0
```

Example 2 -
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-kerberos
  namespace: default
spec:
  type: Python
  pythonVersion: "2"
  mode: cluster
  image: "gcr.io/spark-operator/spark-py:v3.0.0"
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never
  sparkConf:
    "spark.kubernetes.kerberos.krb5.configMapName" : "<KRB5_CONFIG_MAP_NAME>"
    "spark.kubernetes.hadoop.configMapName" : "<HADOOP_CONFIG_MAP_NAME>"
  kerberos:
    enabled: true
	kerberosPrincipal: "<PRINCIPAL>"
	keytabSecret: "<KEYTAB_SECRET>"
	keytabName: "<KEYTAB_FILE_NAME>"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.0.0
```

Hi @chrevanthreddy ,
Its better if we include spark-kerberos examples under examples/.

Thanks and Regards,
Breeta

_Originally posted by @breetasinha1109 in https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1047#issuecomment-731923867_
