### ISSUE TITLE
hostaliases cannot patched to driver or executor pod

### ISSUE THREAD

**Issue by mgyboom** [GoogleCloudPlatform/spark-on-k8s-operator#1760]
I'm sure webhook is enabled.
spark-operator helm values.yaml:
```yaml
replicaCount: 1
image:
  repository: spark-operator
  pullPolicy: IfNotPresent
  tag: v1beta2-1.3.3-3.1.1
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
rbac:
  create: false
  createRole: true
  createClusterRole: true
serviceAccounts:
  spark:
    create: true
    name: spark-datahandler
    annotations: {}
  sparkoperator:
    create: true
    name: spark-operator
    annotations: {}
sparkJobNamespace: ''
controllerThreads: 10
resyncInterval: 30
uiService:
  enable: true
ingressUrlFormat: ''
logLevel: 2
podSecurityContext: {}
securityContext: {}
volumes: []
volumeMounts: []
webhook:
  enable: true
  port: 8080
  namespaceSelector: ''
  initAnnotations:
    helm.sh/hook: 'pre-install, pre-upgrade'
    helm.sh/hook-weight: '50'
  cleanupAnnotations:
    helm.sh/hook: 'pre-delete, pre-upgrade'
    helm.sh/hook-delete-policy: hook-succeeded
  timeout: 30
metrics:
  enable: true
  port: 10254
  portName: metrics
  endpoint: /metrics
  prefix: ''
podMonitor:
  enable: false
  labels: {}
  jobLabel: spark-operator-podmonitor
  podMetricsEndpoint:
    scheme: http
    interval: 5s
nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}
podLabels: {}
resources: {}
batchScheduler:
  enable: false
resourceQuotaEnforcement:
  enable: false
leaderElection:
  lockName: spark-operator-lock
  lockNamespace: ''
istio:
  enabled: false
labelSelectorFilter: ''
```
Job spark-operator-webhook-init is completed.
Deployment spark-operator is Running.

sparkapplication.yaml:
```yaml
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  annotations:
    kubesphere.io/creator: admin
    meta.helm.sh/release-name: spark-d-oxu9xr
    meta.helm.sh/release-namespace: mgy-project
  labels:
    app.kubernetes.io/instance: spark-d-oxu9xr
    app.kubernetes.io/version: 1.2.0
    app.kubesphere.io/instance: spark-d-oxu9xr
  name: spark-d-oxu9xr
  namespace: mgy-project
spec:
  arguments:
    - >-
      {"topic":"test","taskUid":"202305231148","input":{"type":"file","fileSystem":"webhdfs://10.58.10.121:9870","path":"/user/mgy","filename":"server-5w.csv"},"output":{"type":"file","fileSystem":"s3a://mgy","path":"/output/202305231148"},"shardingKey":"1E_ID_md5","shardingNum":10,"shardingType":"HASH"}
  driver:
    cores: 1
    hostAliases:
      - hostnames:
          - zhibang-d-010058010121.hz.td
        ip: 10.58.10.121
    memory: 1g
    memoryOverhead: 1g
    serviceAccount: spark-datahandler
  dynamicAllocation:
    enabled: true
    initialExecutors: 0
    maxExecutors: 4
    minExecutors: 0
  executor:
    cores: 2
    hostAliases:
      - hostnames:
          - zhibang-d-010058010121.hz.td
        ip: 10.58.10.121
    memory: 6g
    memoryOverhead: 2g
  hadoopConf:
    fs.ftp.data.connection.mode: PASSIVE_LOCAL_DATA_CONNECTION_MODE
    fs.s3a.access.key: openpitrixminioaccesskey
    fs.s3a.committer.abort.pending.uploads: 'true'
    fs.s3a.committer.magic.enabled: 'true'
    fs.s3a.endpoint: 'http://minio.kubesphere-system:9000'
    fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
    fs.s3a.path.style.access: 'true'
    fs.s3a.secret.key: openpitrixminiosecretkey
    fs.sftp.impl: org.apache.hadoop.fs.sftp.SFTPFileSystem
    mapreduce.fileoutputcommitter.marksuccessfuljobs: 'false'
    mapreduce.outputcommitter.factory.scheme.s3a: org.apache.hadoop.fs.s3a.commit.S3ACommitterFactory
  image: 'registry.tongdun.me/ibond-ci/spark-datahandler:test'
  imagePullPolicy: IfNotPresent
  mainApplicationFile: 'local:///opt/spark/work-dir/spark-datahandler.jar'
  mainClass: cn.tongdun.sparkdatahandler.app.Sharding
  memoryOverheadFactor: '0.2'
  mode: cluster
  restartPolicy:
    type: Never
  sparkConf:
    spark.default.parallelism: '600'
    spark.dynamicAllocation.shuffleTracking.enabled: 'true'
    spark.executor.heartbeatInterval: 300s
    spark.hadoop.fs.s3a.committer.name: magic
    spark.hadoop.mapreduce.fileoutputcommitter.algorithm.version: '2'
    spark.hadoop.mapreduce.fileoutputcommitter.cleanup-failures.ignored: 'true'
    spark.hadoop.parquet.enable.summary-metadata: 'false'
    spark.kubernetes.driver.volumes.persistentVolumeClaim.spark-local-dir-tmp.mount.path: /export
    spark.kubernetes.driver.volumes.persistentVolumeClaim.spark-local-dir-tmp.mount.readOnly: 'false'
    spark.kubernetes.driver.volumes.persistentVolumeClaim.spark-local-dir-tmp.options.claimName: spark-temp
    spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-tmp.mount.path: /export
    spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-tmp.mount.readOnly: 'false'
    spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-tmp.options.claimName: spark-temp
    spark.network.timeout: 3600s
    spark.speculation: 'false'
    spark.sql.hive.metastorePartitionPruning: 'true'
    spark.sql.parquet.filterPushdown: 'true'
    spark.sql.parquet.mergeSchema: 'false'
    spark.sql.parquet.output.committer.class: org.apache.spark.internal.io.cloud.BindingParquetOutputCommitter
    spark.sql.shuffle.partitions: '500'
    spark.sql.sources.commitProtocolClass: org.apache.spark.internal.io.cloud.PathOutputCommitProtocol
  sparkVersion: 3.1.1
  timeToLiveSeconds: 86400
  type: Java
```
But I can not find hostAliases in driver or executor pod.
I don't know what the problem is.
Can someone help answer that?
