### ISSUE TITLE
Make the operator work for PySpark in spark master

### ISSUE THREAD

**Issue by liyinan926** [GoogleCloudPlatform/spark-on-k8s-operator#181]
The operator currently does not support PySpark, which is available now in the master branch of Spark. The following changes are needed to make the operator support PySpark in the master branch:

* [ ] Make the operator use the new Spark configuration properties introduced in https://github.com/apache/spark/pull/21092.
* [ ] Create a version of the operator image based on a Spark image of the master branch.

**Comment by mrow4a** [comment]
@liyinan926 if this is not high priority for you, you can assign me for this, I will be playing soon with spark master anyways. (1st task only)

CC @prasanthkothuri

**Comment by liyinan926** [comment]
@mrow4a Are you still interested in taking this?

**Comment by mrow4a** [comment]
@liyinan926 Yes, on it now - I see `cluster mode` is broken for us in the master branch https://github.com/apache/spark/blob/master/resource-managers/kubernetes/docker/src/main/dockerfiles/spark/entrypoint.sh#L87

**Comment by mrow4a** [comment]
It appears, that that flag is not taken into account, if specified otherwise by properties file - seems to lunch in cluster mode, but just a printout of driver log is a bit confusing..

**Comment by mrow4a** [comment]
@liyinan926 as I understand by https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/129, the goes is to reuse existing API, right (to freeze it for beta release)

**Comment by liyinan926** [comment]
@mrow4a Can you clarify what you mean by `the goal is to reuse existing API, right (to freeze it for beta release)`?

**Comment by liyinan926** [comment]
Oops, I think I accidentally marked #129 as all done and closed it. The PySpark one is not done yet. Reopened #129.

**Comment by mrow4a** [comment]
@liyinan926 Python works out of the box without `--py-files` dependencies. Now the question is about the api:

```
spec:
  type: Python
  mainApplicationFile: "local:///opt/spark/examples/src/main/python/pi.py"
  deps:
    pyfiles:
      - {{ some-path-to-dependency }}
```

or reusing existing `deps->files` and `type` should resolve it to `--py-files` 


```
spec:
  type: Python
  mainApplicationFile: "local:///opt/spark/examples/src/main/python/pi.py"
  deps:
    files:
      - {{ some-path-to-dependency }}
```

What do you think?
