### ISSUE TITLE
When monitoring enabled, extraJavaOptions is not working

### ISSUE THREAD

**Issue by klu4ic** [GoogleCloudPlatform/spark-on-k8s-operator#1841]
Hello, I'm using the latest version Spark Operator with my Spark Application written on Scala.

I have enable monitoring:

```
monitoring:
  exposeDriverMetrics: true
  exposeExecutorMetrics: true
  prometheus:
    jmxExporterJar: "/opt/spark-dir/lib/jmx_prometheus_javaagent-0.11.0.jar"
    port: 8090
```
Also I have some java extra options:

```
sparkConf:
  spark.driver.extraJavaOptions: "-Dapp.home=/opt//spark-dir -Dlog4j.configuration=file:/opt//spark-dir/conf/log4j.properties"
  spark.executor.extraJavaOptions: "-Dapp.home=/opt//spark-dir -Dlog4j.configuration=file:/opt//spark-dir/conf/log4j.properties"

```

The problem is that when I enable monitoring I lose my extraJavaOptions inside the pod, in sparkapplication manifest or in spark operator pod in logs I see that spark application submitted with extraJavaOptions but if I go inside a pod and check it I see that there are no extraJavaOptions for running process.

kubectl describe sparkapp
```
 Restart Policy:
    Type:  Never
  Spark Conf:
    spark.driver.extraClassPath:             local:///opt/spark-dir/lib/bcprov-jdk15on-1.69.jar:/opt/spark-dir/lib/h2-1.4.200.jar
    spark.driver.extraJavaOptions:           -Dapp.home=/opt/spark-dir -Dlog4j.configuration=file:/opt/spark-dir/conf/log4j.properties
    spark.executor.extraClassPath:           local:///opt/spark-dir/lib/bcprov-jdk15on-1.69.jar:/opt/spark-dir/lib/h2-1.4.200.jar
    spark.exe
```cutor.extraJavaOptions:         -Dapp.home=/opt/spark-dir -Dlog4j.configuration=file:/opt/spark-dir/conf/log4j.properties

```

ps aux in driver pod:

```
spark        1  0.0  0.0   2768   492 ?        Ss   18:58   0:00 /usr/bin/tini -s -- /opt/spark/bin/spark-submit --conf spark.driver.bindAddress=10.104.114.182 --deploy-mode client --properties-file /opt/spark/conf/spark.properties --class com.mycorp.app.base.app local:///opt/spark-dir/lib/app.jar
spark       11  5.3  1.1 41949540 1528060 ?    Sl   18:58   1:00 /opt/java/openjdk/bin/java -cp local:///opt/spark-dir/lib/bcprov-jdk15on-1.69.jar:/opt/spark-dir/lib/h2-1.4.200.jar:/opt/spark/conf/:/opt/spark/jars/* -Xmx30000m -javaagent:/opt/spark-dir/lib/jmx_prometheus_javaagent-0.11.0.jar=8090:/etc/metrics/conf/prometheus.yaml -XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED -Djdk.reflect.useDirectMethodHandle=false org.apache.spark.deploy.SparkSubmit --deploy-mode client --conf spark.driver.bindAddress=10.104.114.182 --properties-file /opt/spark/conf/spark.properties --class com.mycorp.app.base.app local:///opt/spark-dir/lib/app.jar
```
Does anyone know how to solve this problem?

**Comment by klu4ic** [comment]
Moving parameters to the driver and executor javaOptions settings instead of sparkConf resolved the issue.

```
driver:
  javaOptions: "-Dsmbd.home=/opt/smbd -Dlog4j.configuration=file:/opt/spark-dir/conf/log4j.properties" 

executor:
  javaOptions: "-Dsmbd.home=/opt/smbd -Dlog4j.configuration=file:/opt/spark-dir/conf/log4j.properties" 
```
