### ISSUE TITLE
Spark 2.3.1 Support

### ISSUE THREAD

**Issue by ryancampbell** [GoogleCloudPlatform/spark-on-k8s-operator#224]
Hello, chatted in Slack as well, but my team has been trying to switch to Spark 2.3.1 using this guide:
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#customizing-the-spark-operator

After completing the below steps any driver pods immediately fail with "Error: Could not find or load main class <class name here>"

Possibly we are missing a step? Read below. Assistance would be appreciated as 2.3.1 solves a bug in dynamic partition overwrite mode.

Download Spark source code
https://archive.apache.org/dist/spark/spark-2.3.1/spark-2.3.1.tgz

Compile Spark with Kubernetes support
./build/mvn -Pkubernetes -DskipTests clean package

Build Spark 2.3.1 docker image
$ ./bin/docker-image-tool.sh -r gcr.io/uncoil-io/spark -t v2.3.1 build
$ ./bin/docker-image-tool.sh -r gcr.io/uncoil-io/spark -t v2.3.1 push

Clone https://github.com/GoogleCloudPlatform/spark-on-k8s-gcp-examples

Copy conf folder to dockerfiles/spark-gcs

Edit FROM in dockerfiles/spark-gcs/Dockerfile to:
FROM gcr.io/uncoil-io/spark/spark:v2.3.1

Run “gcloud auth configure-docker”

From spark-op-k8s-gcp-examples/dockerfiles/spark-gcs run:

docker build . -t gcr.io/uncoil-io/spark:v2.3.1-gcs
docker push gcr.io/uncoil-io/spark:v2.3.1-gcs

Clone https://github.com/GoogleCloudPlatform/spark-on-k8s-operator
Can checkout master or v1alpha-0.2-2.3.x tag, which ever works in the end

Edit spark-on-k8s-operator/Dockerfile second FROM to be:
FROM gcr.io/uncoil-io/spark:v2.3.1

Run in spark-on-k8s-operator

docker build . -t gcr.io/uncoil-io/spark-operator:v1alpha1-0.2-2.3.1
docker push gcr.io/uncoil-io/spark-operator:v1alpha1-0.2-2.3.1

Edit spark-on-k8s-operator/manifest/spark-operator.yaml
Set image to gcr.io/uncoil-io/spark-operator:v1alpha1-0.2-2.3.1

Delete the sparkoperator namespace
kubectl delete namespace sparkoperator

Delete any sparkapplications as well
kubectl delete sparkapplications --all
kubectl delete scheduledsparkapplications --all

Wait a few minutes.... then
kubectl apply -f spark-on-k8s-operator/manifest/

Check for when ready
kubectl get pods -w --namespace sparkoperator

Edit app.template.yaml and uncoil-runner-yaml:
image: gcr.io/uncoil-io/spark:v2.3.1-gcs
replace 2.3.0 with 2.3.1 in dependencies and the version label

Now see if it works!

**Comment by liyinan926** [comment]
> Edit spark-on-k8s-operator/Dockerfile second FROM to be:
FROM gcr.io/uncoil-io/spark:v2.3.1

Should you be using `FROM gcr.io/uncoil-io/spark:v2.3.1-gcs` instead of `FROM gcr.io/uncoil-io/spark:v2.3.1` in your spark-on-k8s-operator/Dockerfile?

**Comment by ryancampbell** [comment]
@liyinan926 I'll try that again, although I believe I tried both.

I used "gcr.io/uncoil-io/spark:v2.3.1" instead of "gcr.io/uncoil-io/spark:v2.3.1-gcs" because the original Dockerfile used "gcr.io/ynli-k8s/spark:v2.3.0" and not "gcr.io/ynli-k8s/spark:v2.3.0-gcs"

**Comment by liyinan926** [comment]
Can you post your `SparkApplication` spec here?

**Comment by ryancampbell** [comment]
```yaml
apiVersion: "sparkoperator.k8s.io/v1alpha1"
kind: ScheduledSparkApplication
metadata:
  name: uncoil-runner
spec:
  schedule: "@every 5m"
  concurrencyPolicy: Forbid
  template:
    type: Scala
    mode: cluster
    image: gcr.io/uncoil-io/spark:v2.3.1-gcs
    mainClass: uncoil.UncoilRunner
    mainApplicationFile: gs://uncoil-artifacts/uncoil-job/uncoil-job.jar
    deps:
      jars:
        - http://central.maven.org/maven2/org/apache/commons/commons-pool2/2.5.0/commons-pool2-2.5.0.jar
        - http://central.maven.org/maven2/redis/clients/jedis/2.9.0/jedis-2.9.0.jar
        - http://dl.bintray.com/spark-packages/maven/RedisLabs/spark-redis/0.3.2/spark-redis-0.3.2.jar
        - http://central.maven.org/maven2/org/apache/kafka/kafka-clients/0.10.0.1/kafka-clients-0.10.0.1.jar
        - http://central.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.11/2.3.1/spark-sql-kafka-0-10_2.11-2.3.1.jar
        - http://central.maven.org/maven2/org/apache/spark/spark-sql_2.11/2.3.1/spark-sql_2.11-2.3.1.jar
        - http://central.maven.org/maven2/com/typesafe/config/1.3.2/config-1.3.2.jar
        - http://central.maven.org/maven2/mysql/mysql-connector-java/8.0.11/mysql-connector-java-8.0.11.jar
    imagePullPolicy: Always
    hadoopConf:
      "fs.gs.project.id": "uncoil-io"
      "fs.gs.system.bucket": "uncoil-spark-production"
      "google.cloud.auth.service.account.enable": "true"
      "google.cloud.auth.service.account.json.keyfile": "/mnt/secrets/spark-sa.json"
    driver:
      cores: 1
      memory: 3g
      labels:
        version: 2.3.1
      serviceAccount: spark-sa
      secrets:
      - name: "spark-sa"
        path: "/mnt/secrets"
        secretType: GCPServiceAccount
      envVars:
        GCS_PROJECT_ID: uncoil-io
        SCALA_ENV: production
    executor:
      instances: 2
      cores: 2
      memory: 10g
      labels:
        versions: 2.3.1
      secrets:
      - name: "spark-sa"
        path: "/mnt/secrets"
        secretType: GCPServiceAccount
      envVars:
        GCS_PROJECT_ID: uncoil-io
        SCALA_ENV: production
```
