### ISSUE TITLE
pyspark arguments issue

### ISSUE THREAD

**Issue by u2takey** [GoogleCloudPlatform/spark-on-k8s-operator#273]
run pyspark with arguments

```
spec:
  command: 
  - "test.py"
  arguments:
  - "1"
  - "2"
  - "3"
```
what i got in driver is `test.py 1,2,3`, not `test.py 1 2 3` as i expected. And in Driver Env, I found related env 
```
    - name: PYSPARK_APP_ARGS
      value: 1,2,3
```
