### ISSUE TITLE
Running SparkPi Example

### ISSUE THREAD

**Issue by deyceg** [GoogleCloudPlatform/spark-on-k8s-operator#322]
@liyinan926 Maybe just a question rather than a bug as I suspect it works for others...

Deployed the operator as per instructions, and created the example application in the repo but the driver pod's `spark-submit` command fails because the container arguments are _just_ "driver":

```
    CMD=(
      "$SPARK_HOME/bin/spark-submit"
      --conf "spark.driver.bindAddress=$SPARK_DRIVER_BIND_ADDRESS"
      --deploy-mode client
      "$@"
```

"driver" is shifted so `$@` is empty!

It looks as though it would work for executor as all the submit options (what you see in the operator logs/submission runner) are now environment variables to be used as JAVA_OPTS.

**Comment by deyceg** [comment]
downgrading to 2.3.1 fixes the issue so need to check the diff between the two unified images!

**Comment by andrewgdavis** [comment]
ran into what seems to be the same issue.   the old sparkoperator was deployed:
```
  sparkoperator:
    Container ID:  docker://f2b06ae7ae36bb17499171e09bc6875522786b09ff954e06f82601822fc1f4bb
    Image:         gcr.io/spark-operator/spark-operator:v2.3.1-v1alpha1-latest
    Image ID:      docker-pullable://gcr.io/spark-operator/spark-operator@sha256:c498b6f1368af5bb3b76af11aa60c07dd81455f62c16cb630b9a3c54c74b03a7
```
and trying the getting started example (which changed to v2.4.0)
```
kubectl -n kubeflow apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/spark-on-k8s-operator/master/examples/spark-pi.yaml
```
would result in 
```
spark-pi-e6066a55942f3244988daf9c9d9adb92-driver         0/1       Error        0          24m
```
with no logs.
----
using the example prior to v2.4.0 support worked:
```
apiVersion: "sparkoperator.k8s.io/v1alpha1"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v2.3.1"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.11-2.3.1.jar"
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 0.1
    coreLimit: "200m"
    memory: "512m"
    labels:
      version: 2.3.1
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.3.1
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  restartPolicy: Never
```
