### ISSUE TITLE
Running simple SparkOperator

### ISSUE THREAD

**Issue by roksolana-d** [GoogleCloudPlatform/spark-on-k8s-operator#323]
I have tried to run SparkOperator with simple example of SparkPi. I have tested this before using spark-submit and everything works properly. However, I get ImagePullErrors on pods when I try to run the application with SparkOperator. What could be the cause of it? Is that serviceaccounts problem?

Steps to reproduce:
1. I have create service account and role for Spark
```
kubectl create serviceaccount spark
kubectl create clusterrolebinding spark-role --clusterrole=edit --serviceaccount=default:spark --namespace=default
```

2. I have installed helm with minikube
3. Added spark operator repo 
```
helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator
helm install incubator/sparkoperator --namespace default
```

4. Then I have defined my spark application in yaml file and executed with this comand:
`kubectl apply -f examples/spark-pi.yaml`

5. This is how the status of pods in the default namespace looks like

```
NAME                                        READY   STATUS    RESTARTS   AGE
jolly-bear-sparkoperator-599d667f98-8xnz5   1/1     Running   3          15h
spark-pi-5961c7817841391f8d249d3a1b12b4f5-driver   0/1   Pending   0     0s
spark-pi-5961c7817841391f8d249d3a1b12b4f5-driver   0/1   Pending   0     0s
spark-pi-5961c7817841391f8d249d3a1b12b4f5-driver   0/1   Init:0/1   0     0s
spark-pi-5961c7817841391f8d249d3a1b12b4f5-driver   0/1   Init:Error   0     3s
```
Driver pod logs:

`Error from server (BadRequest): container "spark-kubernetes-driver" in pod "spark-pi-5961c7817841391f8d249d3a1b12b4f5-driver" is waiting to start: PodInitializing`

While sparkoperator logs contain this message:

`submission_runner.go:99] spark-submit completed for SparkApplication spark-pi in namespace default`

kubectl get serviceaccounts command returns this:

```
NAME                       
default              
jolly-bear-spark      
jolly-bear-sparkoperator   
spark                 
```
And spark-application.yaml file contents:

```
apiVersion: sparkoperator.k8s.io/v1alpha1
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  image: roksolanad/spark-2.4.0-k8s
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: local:///tmp/jars/spark-examples_2.11-2.4.0.jar
  mode: cluster
  deps: {}
  driver:
    coreLimit: 1000m
    cores: 0.1
    labels:
      version: 2.4.0
    memory: 1024m
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    labels:
      version: 2.4.0
    memory: 1024m
  imagePullPolicy: Never
  restartPolicy: Never

```

The image was build from this Dockerfile:

```
FROM gcr.io/spark-operator/spark:v2.4.0
COPY jars/spark-examples_2.11-2.4.0.jar /tmp/jars/spark-examples_2.11-2.4.0.jar

```
