### ISSUE TITLE
Spark driver and executors pods are not created

### ISSUE THREAD

**Issue by roksolana-d** [GoogleCloudPlatform/spark-on-k8s-operator#348]
I have installed Spark operator with Helm package. However, when I apply yaml file with custom object definition the custom object is created but not the pods - nor Spark driver, nor executor pods.  Standard spark-operator deployment and the pod are created.
Could there be some permissions problem? Although, I have created the cluster role according to the quick start guide. What could be the reason of this problem?

These are the sequence of command I have executed:

1) `helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator`
2) `helm install incubator/sparkoperator --namespace default`
3) `kubectl describe clusterrolebinding/spark-role`

```
Name:         spark-role
Labels:       <none>
Annotations:  <none>
Role:
  Kind:  ClusterRole
  Name:  edit
Subjects:
  Kind            Name   Namespace
  ----            ----   ---------
  ServiceAccount  spark  default
```

This is my yaml file with the custom resource definition:
```
apiVersion: sparkoperator.k8s.io/v1alpha1
kind: SparkApplication
metadata:
  name: spark-example
  namespace: default
spec:
  type: Scala
  image: gcr.io/ynli-k8s/spark:v2.4.0
  mainClass: org.apache.spark.examples.SparkExample
  mainApplicationFile: http://localhost:8088/my_jar.jar
  mode: cluster
  deps: {}
  driver:
    coreLimit: 1000m
    cores: 0.1
    labels:
      version: 2.4.0
    memory: 1024m
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    labels:
      version: 2.4.0
    memory: 1024m
  imagePullPolicy: Never
  restartPolicy: Never
```
