### ISSUE TITLE
Does MainApplicationFile supports use of a remote url for the spark application file? What other formats are supported?

### ISSUE THREAD

**Issue by dileepranganathan** [GoogleCloudPlatform/spark-on-k8s-operator#350]

**Comment by liyinan926** [comment]
Yes, it supports `http://`, `hdfs://`, `s3a://`, `gcs://`, and any URLs of some remote storage compatible with the Hadoop file system API.

**Comment by liyinan926** [comment]
Closing. Feel free to reopen if you have more questions.

**Comment by Nj-kol** [comment]
If I specify `mainApplicationFile: http://<some_url>` and the url has basic auth, how do I specify the credentials

**Comment by m-gavrilyuk** [comment]
> If I specify `mainApplicationFile: http://<some_url>` and the url has basic auth, how do I specify the credentials

did you find the way download jar with basic auth ? @Nj-kol

**Comment by Nj-kol** [comment]
> > If I specify `mainApplicationFile: http://<some_url>` and the url has basic auth, how do I specify the credentials
> 
> did you find the way download jar with basic auth ? @Nj-kol

No, what we ended up doing is to create an init container that fetches the jar from nexus and then use `mainApplicationFile: [local](local:///opt/spark/app/myapp.jar)`

**Comment by m-gavrilyuk** [comment]
> > > If I specify `mainApplicationFile: http://<some_url>` and the url has basic auth, how do I specify the credentials
> > 
> > 
> > did you find the way download jar with basic auth ? @Nj-kol
> 
> No, what we ended up doing is to create an init container that fetches the jar from nexus and then use `mainApplicationFile: local:///opt/spark/app/myapp.jar`

Can you share example mainfist 
I try 
```
apiVersion: sparkoperator.k8s.io/v1beta2
kind: ScheduledSparkApplication
metadata:
  name: {{.Release.Name}}
spec:
  concurrencyPolicy: Forbid
  failedRunHistoryLimit: 2
  successfulRunHistoryLimit: 2
  schedule: {{.Values.spark.schedule|quote}}
  template:
    image: {{.Values.spark_image.repository}}:{{.Values.spark_image.tag}}
    imagePullPolicy: {{.Values.spark_image.pullPolicy}}
    mainApplicationFile: local:///download/my-assembly.jar
    mainClass: {{.Values.spark.mainClass}}
    mode: cluster
    restartPolicy:
    sparkVersion: 3.5.0
    type: Scala
    driver:
      initContainers:
      - name: jar-download
        image: {{.Values.spark_image.repository}}:{{.Values.spark_image.tag}}
        workingDir: /download/
        command: ["/bin/sh"]
        args:
          - -c
          - wget "https://$NEXUS_USERNAME:$NEXUS_PASSWORD@nexus.com/repository/my-repo/my-assembly.jar"
        env:
          - name: NEXUS_USERNAME
            valueFrom:
              secretKeyRef:
                key: NEXUS_USERNAME
                name:  nexus-auth
          - name: NEXUS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: NEXUS_PASSWORD
                name:  nexus-auth
        volumeMounts:
          - mountPath: /download/
            name: main-jar
      volumeMounts:
        - mountPath: /download/
          name: main-jar
    executor:
      volumeMounts:
        - mountPath: /download/
          name: main-jar
    volumes:
    - name:  main-jar
      emptyDir: {}
  ``` 
but my executors failed with error 
 Lost an executor 17 (already removed): Unable to create executor due to /download/my-assembly.jar

**Comment by Nj-kol** [comment]
> > > > If I specify `mainApplicationFile: http://<some_url>` and the url has basic auth, how do I specify the credentials
> > > 
> > > 
> > > did you find the way download jar with basic auth ? @Nj-kol
> > 
> > 
> > No, what we ended up doing is to create an init container that fetches the jar from nexus and then use `mainApplicationFile: local:///opt/spark/app/myapp.jar`
> 
> Can you share example mainfist I try
> 
> ```
> apiVersion: sparkoperator.k8s.io/v1beta2
> kind: ScheduledSparkApplication
> metadata:
>   name: {{.Release.Name}}
> spec:
>   concurrencyPolicy: Forbid
>   failedRunHistoryLimit: 2
>   successfulRunHistoryLimit: 2
>   schedule: {{.Values.spark.schedule|quote}}
>   template:
>     image: {{.Values.spark_image.repository}}:{{.Values.spark_image.tag}}
>     imagePullPolicy: {{.Values.spark_image.pullPolicy}}
>     mainApplicationFile: local:///download/my-assembly.jar
>     mainClass: {{.Values.spark.mainClass}}
>     mode: cluster
>     restartPolicy:
>     sparkVersion: 3.5.0
>     type: Scala
>     driver:
>       initContainers:
>       - name: jar-download
>         image: {{.Values.spark_image.repository}}:{{.Values.spark_image.tag}}
>         workingDir: /download/
>         command: ["/bin/sh"]
>         args:
>           - -c
>           - wget "https://$NEXUS_USERNAME:$NEXUS_PASSWORD@nexus.com/repository/my-repo/my-assembly.jar"
>         env:
>           - name: NEXUS_USERNAME
>             valueFrom:
>               secretKeyRef:
>                 key: NEXUS_USERNAME
>                 name:  nexus-auth
>           - name: NEXUS_PASSWORD
>             valueFrom:
>               secretKeyRef:
>                 key: NEXUS_PASSWORD
>                 name:  nexus-auth
>         volumeMounts:
>           - mountPath: /download/
>             name: main-jar
>       volumeMounts:
>         - mountPath: /download/
>           name: main-jar
>     executor:
>       volumeMounts:
>         - mountPath: /download/
>           name: main-jar
>     volumes:
>     - name:  main-jar
>       emptyDir: {}
> ```
> 
> but my executors failed with error Lost an executor 17 (already removed): Unable to create executor due to /download/my-assembly.jar

For official reasons, I can't specify the exact implementation. But you have to have the init container on both driver and executor. It should look something like :

```yaml
spec:
  mainApplicationFile: local:///opt/spark/app/<some_name>-$APP_VERSION..jar
  mainClass: com.myorg.YouSparkApp
  driver:
  	...
    initContainers:
    - args:
      - curl -u $NEXUS_USERNAME:$NEXUS_PASSWORD -o /opt/spark/app/<some_name>-$APP_VERSION.jar
        $NEXUS_BASE_URL/<some_path>/<some_name>_2.12/$APP_VERSION/<some_name>_2.12-$APP_VERSION.jar
      command:
      - sh
      - -c
      env:
      - name: NEXUS_USERNAME
        value: ******
      - name: NEXUS_PASSWORD
        value: ******
      - name: NEXUS_BASE_URL
        value: https://nexus.<something>.org/nexus/service/local/repositories/<your_repo_name>/content
      - name: APP_VERSION
        value: 1.2.0
      image: curlimages/curl:latest
      name: download-jar
      resources:
        limits:
          cpu: 50m
          memory: 0.25Gi
        requests:
          cpu: 50m
          memory: 0.25Gi
      volumeMounts:
      - mountPath: /opt/spark/app
        name: app-jar

  executor:
  	...
    initContainers:
    - args:
      - curl -u $NEXUS_USERNAME:$NEXUS_PASSWORD -o /opt/spark/app/<some_name>-$APP_VERSION.jar
        $NEXUS_BASE_URL/<some_path>/<some_name>_2.12/$APP_VERSION/<some_name>_2.12-$APP_VERSION.jar
      command:
      - sh
      - -c
      env:
      - name: NEXUS_USERNAME
        value: ******
      - name: NEXUS_PASSWORD
        value: ******
      - name: NEXUS_BASE_URL
        value: https://nexus.<something>.org/nexus/service/local/repositories/<your_repo_name>/content
      - name: APP_VERSION
        value: 1.2.0
      image: curlimages/curl:latest
      name: download-jar
      resources:
        limits:
          cpu: 50m
          memory: 0.25Gi
        requests:
          cpu: 50m
          memory: 0.25Gi
      volumeMounts:
      - mountPath: /opt/spark/app
        name: app-jar
```
