### ISSUE TITLE
ErrImagePull with custom Spark operator image

### ISSUE THREAD

**Issue by roksolana-d** [GoogleCloudPlatform/spark-on-k8s-operator#356]
I am trying to build a custom spark-operator image without Helm. So I tried to build Dockerfile in a cluster for that.  The Dockerfile is in the master branch. For Kubernetes I use Minikube.

This is the sequence of command I have executed:
1) `eval $(minikube docker-env)
`
2) `docker build -t in-cluster .` (in a directory with Dockerfile)

The delpoyment is created but Pod status shows such message:  `ErrImagePull`

What should I change to fix this error? 
I also tried to create a deployment manually but the results were the same.

The steps:
1) Downloaded this repository
2)  `docker build -t spark:2.4.0 .`

Spark-operator deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-operator-custom
  labels:
    role: spark-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      role: spark-operator
  template:
    metadata:
      labels:
        role: spark-operator
    spec:
      serviceAccountName: spark
      containers:
        - name: spark-operator-custom
          image: spark:2.4.0
```

**Comment by liyinan926** [comment]
Where did you push your image to?

**Comment by roksolana-d** [comment]
I didn't push it. I use it locally

**Comment by roksolana-d** [comment]
UPDATE: I pushed the image to DockerHub. When I tried to use it in the deployment I get such behavior:

```
sparkoperator   0/1   Pending   0     0s
sparkoperator   0/1   Pending   0     0s
sparkoperator   0/1   ContainerCreating   0     0s
sparkoperator   0/1   Error   0     5s
sparkoperator   0/1   Error   1     8s
sparkoperator  0/1   CrashLoopBackOff   1     9s
```
Same when I run the image in-cluster using `docker run`.
Here is the deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-operator-custom
  labels:
    role: spark-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      role: spark-operator
  template:
    metadata:
      labels:
        role: spark-operator
    spec:
      serviceAccountName: spark
      containers:
        - name: spark-operator-custom
          image: roksolanad/spark-in-cluster:v2.4.0
```
