### ISSUE TITLE
Directories are not mounted in the driver pod

### ISSUE THREAD

**Issue by apryiomka** [GoogleCloudPlatform/spark-on-k8s-operator#359]
Bellow is the py-pi example
```
apiVersion: "sparkoperator.k8s.io/v1alpha1"
kind: SparkApplication
metadata:
  name: pyspark-pi
  namespace: default
spec:
  type: Python
  pythonVersion: "2"
  mode: cluster
  image: "gcr.io/spark-operator/spark-py:v2.4.0"
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  volumes:
    - hostPath:
        path: /Users/user/.aws
        type: Directory
      name: aws
  driver:
    cores: 0.1
    coreLimit: "200m"
    memory: "512m"
    labels:
      version: 2.4.0
    serviceAccount: spark
    volumeMounts:
      - mountPath: /root/.aws
        name: aws
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.0
```
I am running spark application in minikube that has `/Users/user/.aws` mounted from the host. I am trying to mount that directory from minikube inside the pod and it does't work. It works just fine with spark submit though:
```
--conf spark.kubernetes.driver.volumes.hostPath.aws.mount.path=/root/.aws \
--conf spark.kubernetes.driver.volumes.hostPath.aws.options.path=/Users/user/.aws
```
