### ISSUE TITLE
File for spark application is not found

### ISSUE THREAD

**Issue by roksolana-d** [GoogleCloudPlatform/spark-on-k8s-operator#365]
I have defined a file for Spark application execution which is passed as an argument to the class. However, each time I create a custom object I get an error:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at example.SparkExample$.main(SparkExample.scala:37)
	at example.SparkExample.main(SparkExample.scala)
...
```
This exception point to the SparkExample.scala:37 where I read class arguments:

`  val dataFromFile = readFile(spark.sparkContext, args(0))`

Although, I have defined this argument as a file in deps section for the custom object. What may be the reason of this problem?
I checked that the file can be accessed by the provided link.
Here is a custom object definition:

```
apiVersion: sparkoperator.k8s.io/v1alpha1
kind: SparkApplication
metadata:
  name: spark-example
  namespace: default
spec:
  type: Scala
  image: gcr.io/ynli-k8s/spark:v2.4.0-SNAPSHOT
  mainClass: example.SparkExample
  mainApplicationFile: http://192.168.99.100:8089/spark_k8s_airflow.jar
  mode: cluster
  deps:
    files:
      - http://192.168.99.100:8089/jar_test_data.txt
  driver:
    coreLimit: 1000m
    cores: 0.1
    labels:
      version: 2.4.0
    memory: 1024m
    serviceAccount: default
  executor:
    cores: 1
    instances: 1
    labels:
      version: 2.4.0
    memory: 1024m
  imagePullPolicy: Always
```
