### ISSUE TITLE
How to pass in application arguments in yaml file?

### ISSUE THREAD

**Issue by JoeyLuffa** [GoogleCloudPlatform/spark-on-k8s-operator#380]
Using `spark-submit`, I can pass in `application-arguments` at the end:
```
./bin/spark-submit \
  --class <main-class> \
  --master <master-url> \
  --deploy-mode <deploy-mode> \
  --conf <key>=<value> \
  ... # other options
  <application-jar> \
  [application-arguments]
```

I am wondering what's the syntax of passing in these `application-arguments` in yaml files? 

Thanks.

**Comment by liyinan926** [comment]
```yaml
spec:
    arguments:
    - arg1
    - arg2
```

**Comment by JoeyLuffa** [comment]
@liyinan926 thanks. For instance, if my `application-arguments` is:
```
 --kafka-bootstrap-servers kafka:9092
```
in the `spark-submit` command. What's the best way to convert it to the arguments section? Like this?

```yaml
spec:
    arguments:
    - --kafka-bootstrap-servers
    - kafka:9092
```
