### ISSUE TITLE
Quick question: why the number of cores for the driver pod is 0.1?

### ISSUE THREAD

**Issue by JoeyLuffa** [GoogleCloudPlatform/spark-on-k8s-operator#386]
```
driver:
    cores: 0.1
    coreLimit: "200m"
    memory: "512m"
```

Not quite understand the 0.1 here.
