### ISSUE TITLE
Spark application master defined as an option

### ISSUE THREAD

**Issue by roksolana-d** [GoogleCloudPlatform/spark-on-k8s-operator#389]
I defined master for Spark application as an application argument. So when I try to define Spark application custom object I have to define the link to the master of the application as an argument. Is there any option to define it as application master so it would look like this `master: url`?

Here is how it looks in code:

```
val spark = SparkSession
      .builder
      .master(args(0))
      .appName("TestApp")
      .getOrCreate()


```

And this is the config in yaml file:
```

apiVersion: sparkoperator.k8s.io/v1alpha1
kind: SparkApplication
metadata:
  name: spark-example
  namespace: default
spec:
  type: Scala
  image: gcr.io/ynli-k8s/spark:v2.4.0-SNAPSHOT
  mainClass: example.SparkAppExample
  mainApplicationFile: local:///tmp/spark_app_example.jar
  mode: cluster
  arguments:
    - "k8s://https://192.168.99.100:8443"
etc.
```
