### ISSUE TITLE
Driver pod ownerReference does not have controller flag set

### ISSUE THREAD

**Issue by andremarianiello** [GoogleCloudPlatform/spark-on-k8s-operator#394]
Driver pod owner references:

```yaml
  ownerReferences:
  - apiVersion: sparkoperator.k8s.io/v1alpha1
    kind: SparkApplication
    name: aggregation
    uid: 7e4686b1-2638-11e9-b233-42010a800004
```

`controller` is null. Is this intentional or a very tiny oversight?
