### ISSUE TITLE
Log4j can't be overrided from the classpath or files section

### ISSUE THREAD

**Issue by roksolana-d** [GoogleCloudPlatform/spark-on-k8s-operator#395]
I am trying to redefine log4j file for the Spark application. I set it up in the src/main/resources folder. So this file is in the jar file. In this log4j file, I defined output in the JSON format. 
When I run Spark application with Spark operator the logs are in the standard format. I tried to get Log4j debug output: 

```
log4j: Trying to find [log4j.xml] using context classloader sun.misc.Launcher$AppClassLoader@bebdb06.
log4j: Trying to find [log4j.xml] using sun.misc.Launcher$AppClassLoader@bebdb06 class loader.
log4j: Trying to find [log4j.xml] using ClassLoader.getSystemResource().
log4j: Trying to find [log4j.properties] using context classloader sun.misc.Launcher$AppClassLoader@bebdb06.
log4j: Using URL [jar:file:/opt/spark/jars/kubernetes-model-2.0.0.jar!/log4j.properties] for automatic log4j configuration.
log4j: Reading configuration from URL jar:file:/opt/spark/jars/kubernetes-model-2.0.0.jar!/log4j.properties
log4j: Parsing for [root] with value=[INFO, stdout].
```

So it looks like my log4j file is not found. I defined it as a file in Spark application custom object definition but the file is still not resolved and the output in the debug is just the same. 
Why Log4j is not found in the classpath and why it is not loaded from the files section?

 Here is my Spark application configuration:

```
apiVersion: sparkoperator.k8s.io/v1alpha1
kind: SparkApplication
metadata:
  name: spark-example
  namespace: default
spec:
  type: Scala
  image: gcr.io/spark-operator/spark:v2.4.0-gcs-prometheus
  mainClass: example.SparkAppExample
  mainApplicationFile: local:///tmp/spark_app_example_2.jar
  mode: cluster
  sparkConf:
    "spark.driver.extraJavaOptions": "-Dlog4j.debug"
  files:
    - file:///tmp/log4j.xml
  arguments:
    - "k8s://https://192.168.99.100:8443"
  volumes:
    - name: jar-pv-storage
      hostPath:
        path: /hosthome/roksolana/Documents/WORK/TBC/tbc/Spark_App_CI_CD/target/scala-2.11
        type: Directory
  driver:
    coreLimit: 1000m
    cores: 0.1
    labels:
      version: 2.4.0
    memory: 1024m
    serviceAccount: default
    volumeMounts:
      - name: jar-pv-storage
        mountPath: /tmp
  executor:
    cores: 1
    instances: 1
    labels:
      version: 2.4.0
    memory: 1024m
    volumeMounts:
      - name: jar-pv-storage
        mountPath: /tmp
  imagePullPolicy: Always
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/prometheus/jmx_prometheus_javaagent-0.3.1.jar"
      port: 8090
```

**Comment by liyinan926** [comment]
Are you expecting the file `log4j.properties` in `/opt/spark/jars/kubernetes-model-2.0.0.jar` or `local:///tmp/spark_app_example_2.jar`?

**Comment by roksolana-d** [comment]
I expect it in mounted jar file as a volume which is 'local:///tmp/spark_app_example_2.jar'

**Comment by liyinan926** [comment]
Based on the logs, `log4j.properties` in `/opt/spark/jars/kubernetes-model-2.0.0.jar` gets picked up.

**Comment by roksolana-d** [comment]
Exactly, it looks like it. So how my custom log4j file can be picked up?

**Comment by liyinan926** [comment]
You can try to do the following:

1. Put your custom log4j.properties into your image:

```
spec:
    driver:
        javaOptions: -Dlog4j.configuration=/path/to/log4j.properties
    executor:
        javaOptions: -Dlog4j.configuration=/path/to/log4j.properties
```

**Comment by roksolana-d** [comment]
I use the standard image `gcr.io/spark-operator/spark:v2.4.0-gcs-prometheus` for the Spark application custom object. So should I add a log4j file by creating my own image based on this image?

**Comment by liyinan926** [comment]
Yes, you will need to build a custom image. You can put your `log4j.properties` under `/opt/spark/conf` in the image.

**Comment by roksolana-d** [comment]
But is that possible to get a log4j file as mounted config map instead of building custom image?

**Comment by liyinan926** [comment]
Oh, yeah, you can use a ConfigMap.

**Comment by roksolana-d** [comment]
For some reason, the configmap is mounted but my custom log4j file is still not resolved:

`Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties`

Spark application custom object looks like this:

```
apiVersion: sparkoperator.k8s.io/v1alpha1
kind: SparkApplication
metadata:
  name: spark-example
  namespace: default
spec:
  type: Scala
  image: gcr.io/spark-operator/spark:v2.4.0-gcs-prometheus
  mainClass: example.SparkAppExample
  mainApplicationFile: local:///tmp/spark_app_example_log4j.jar
  mode: cluster
  arguments:
    - "k8s://https://192.168.99.100:8443"
  volumes:
    - name: jar-pv-storage
      hostPath:
        path: /hosthome/roksolana/Documents/WORK/TBC/tbc/Spark_App_CI_CD/target/scala-2.11
        type: Directory
    - name: log4j-config
      configMap:
        name: log4j
  driver:
    coreLimit: 1000m
    cores: 0.1
    labels:
      version: 2.4.0
    memory: 1024m
    serviceAccount: default
    volumeMounts:
      - name: jar-pv-storage
        mountPath: /tmp
      - name: log4j-config
        mountPath: /tmp/log4j
    javaOptions: "-Dlog4j.configuration=/tmp/log4j/log4j.xml"
  executor:
    cores: 1
    instances: 1
    labels:
      version: 2.4.0
    memory: 1024m
    volumeMounts:
      - name: jar-pv-storage
        mountPath: /tmp
      - name: log4j-config
        mountPath: /tmp/log4j
    javaOptions: "-Dlog4j.configuration=/tmp/log4j/log4j.xml"
```
