### ISSUE TITLE
kubectl apply -f does not restart spark application

### ISSUE THREAD

**Issue by nikkatalnikov** [GoogleCloudPlatform/spark-on-k8s-operator#400]
To restart my Spark app, I have to execute:

kubectl apply -f k8s/spark/spark-prometheus.yaml
kubectl delete -f k8s/spark/spark-prometheus.yaml

while in Use Guide --> Updating Spark application it is said that kubectl apply would be enough to restart.
 
Status after something fails in the code:
➜  k8s-spark-kafka-hdfs kubectl describe -f k8s/spark/spark-prometheus.yaml

```
Name:         spark-pi
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"sparkoperator.k8s.io/v1beta1","kind":"SparkApplication","metadata":{"annotations":{},"name":"spark-pi","namespace":"default"},"spec":{"d...
API Version:  sparkoperator.k8s.io/v1beta1
Kind:         SparkApplication
Metadata:
  Creation Timestamp:  2019-02-11T16:27:23Z
  Generation:          5
  Resource Version:    95342
  Self Link:           /apis/sparkoperator.k8s.io/v1beta1/namespaces/default/sparkapplications/spark-pi
  UID:                 e91e3ab6-2e19-11e9-be02-080027d409b2
Spec:
  Deps:
  Driver:
    Core Limit:  200m
    Cores:       0.1
    Labels:
      Version:        2.4.0
    Memory:           512m
    Service Account:  default
  Executor:
    Cores:      1
    Instances:  1
    Labels:
      Version:            2.4.0
    Memory:               512m
  Image:                  gcr.io/spark-operator/spark:v2.4.0-gcs-prometheus
  Image Pull Policy:      Always
  Main Application File:  http://192.168.99.1:8080/k8s-spark-kafka-hdfs-assembly-0.1.jar
  Main Class:             producer.SparkRunner
  Mode:                   cluster
  Monitoring:
    Expose Driver Metrics:    true
    Expose Executor Metrics:  true
    Prometheus:
      Configuration:     <nil>
      Jmx Exporter Jar:  /prometheus/jmx_prometheus_javaagent-0.3.1.jar
      Port:              8090
  Restart Policy:
    Type:         Never
  Spark Version:  2.4.0
  Type:           Scala
Status:
  Application State:
    Error Message:  
    State:          FAILED
  Driver Info:
    Pod Name:                    spark-pi-driver
    Web UI Port:                 31484
    Web UI Service Name:         spark-pi-ui-svc
  Execution Attempts:            1
  Last Submission Attempt Time:  2019-02-11T16:27:26Z
  Spark Application Id:          spark-f5055d5e22fa457fa8c51ecb6d44618d
  Submission Attempts:           1
  Termination Time:              2019-02-11T16:28:10Z
Events:
  Type     Reason                     Age              From            Message
  ----     ------                     ----             ----            -------
  Normal   SparkApplicationAdded      2m (x2 over 2m)  spark-operator  SparkApplication spark-pi was added, Enqueuing it for submission
  Normal   SparkApplicationSubmitted  2m               spark-operator  SparkApplication spark-pi was submitted successfully
  Normal   SparkDriverRunning         1m (x3 over 1m)  spark-operator  Driver spark-pi-driver is running
  Warning  SparkDriverFailed          1m               spark-operator  Driver spark-pi-driver failed
  Warning  SparkApplicationFailed     1m               spark-operator  SparkApplication spark-pi terminated with state: FAILED

```

my spark configuration 

```
apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v2.4.0-gcs-prometheus"
  imagePullPolicy: Always
  mainClass: producer.SparkRunner
  mainApplicationFile: "http://192.168.99.1:8080/k8s-spark-kafka-hdfs-assembly-0.1.jar"
  sparkVersion: "2.4.0"
  restartPolicy:
    type: Never
  driver:
    cores: 0.1
    coreLimit: "200m"
    memory: "512m"
    labels:
      version: 2.4.0
    serviceAccount: default
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.0
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/prometheus/jmx_prometheus_javaagent-0.3.1.jar"
      port: 8090
```
