### ISSUE TITLE
Driver pod not created after erroneous SparkApplication

### ISSUE THREAD

**Issue by ashmitaraju** [GoogleCloudPlatform/spark-on-k8s-operator#402]
After running an erroneous sparkApplication, subsequent correct applications are not being executed. Driver pods and logs for the subsequent application are not generated.

Upon running a spark application which had an error in the yaml ( Arguments was not given as a list ),  the driver pod was not created. 

Yaml: 

```
apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: spark-wordcount
  namespace: spark-pod
spec:
  type: Python
  pythonVersion: "2"
  mode: cluster
  image: "docker.io/rmy1997/wordcount"
  imagePullPolicy: Always
  mainApplicationFile: local:////opt/spark/examples/wordcount.py
  arguments: local:////opt/spark/examples/wordcount.py
  sparkVersion: "2.4.0"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 0.1
    coreLimit: "200m"
    memory: "512m"
    labels:
      version: 2.4.0
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.0
```

The spark-operator pod logs had the following error : 
```
 ...
E0212 07:12:04.348008      11 reflector.go:205] github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: Failed to list *v1beta1.SparkApplication: v1beta1.SparkApplicationList.Items: []v1beta1.SparkApplication: v1beta1.SparkApplication.Spec: v1beta1.SparkApplicationSpec.Arguments: []string: decode slice: expect [ or n, but found ", error found in #10 byte of ...|guments":"local:///o|..., bigger context ...|e95-11e9-ad76-52eca367ca6c"},"spec":{"arguments":"local:///opt/spark/examples/src/main/python/wordco|... 
``` 

When a subsequent valid spark application was created on the same spark-operator, this sparkapplication did not create a driver pod, or sometimes created a pod after a delay of about 30 minutes. 

Valid yaml: 

```
apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: spark-pi-direct
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v2.4.0"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.11-2.4.0.jar"
  sparkVersion: "2.4.0"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 0.1
    coreLimit: "200m"
    memory: "512m"
    labels:
      version: 2.4.0
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.0
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp" 
```

On deleting the erroneous sparkapplication, the valid ones created driver pods and completed. 

Actual Output: Logs of the second SparkApplication not to be seen. Only erroneous logs visible on spark-operator pod. No pods created for either application.
Expected output: Logs indicating the status of the second SparkApplication. Correct sparkApplication must run successfully by creating a driver pod.

P.S. Could not get access to the [Slack Channel](https://kubernetes.slack.com/). Could you please send us an invite. - ashmita.raju@gmail.com, ramya.ramanathan28@gmail.com and rachit1arora@gmail.com
