### ISSUE TITLE
Executor pod memory always is 1184Mi regardless of configuration

### ISSUE THREAD

**Issue by thangbn** [GoogleCloudPlatform/spark-on-k8s-operator#432]
Have a Spark application submit using below manifest:
```yaml
apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: es
  namespace: default
spec:
  nodeSelector:
    "node-type": "high-cpu"
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "gcr.io/equity-ai/metric-pipeline-spark:47"
  imagePullPolicy: Always
  mainApplicationFile: local:///app/batch_spark/spark_batch_main.py
  arguments:
  - "--BIGQUERY_DATASET_ID=prod_v2_new"
  - "--BIGQUERY_PROJECT_ID=equity-ai"
  sparkVersion: "2.4.0"
  sparkConf:
    "spark.serializer": "org.apache.spark.serializer.KryoSerializer"
    "spark.default.parallelism": "100"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 0.5
    memory: "1800m"
    labels:
      version: 2.4.0
    serviceAccount: default
  executor:
    cores: 1
    instances: 30
    memory: 800m
    labels:
      version: 2.4.0
```

Tried to tweak the **executor.memory** value but no matter what value I put there the memory request by executor is always 1184Mi.
```json
{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "es-1552005039106-exec-1",
    "namespace": "default",
    "selfLink": "/api/v1/namespaces/default/pods/es-1552005039106-exec-1",
    "uid": "f3430518-4139-11e9-bdbe-42010a8000bb",
    "resourceVersion": "63632282",
    "creationTimestamp": "2019-03-08T00:34:36Z",
    "deletionTimestamp": "2019-03-08T00:40:30Z",
    "deletionGracePeriodSeconds": 30,
    "labels": {
      "spark-app-selector": "spark-application-1552005275761",
      "spark-exec-id": "1",
      "spark-role": "executor",
      "sparkoperator.k8s.io/app-name": "es",
      "sparkoperator.k8s.io/launched-by-spark-operator": "true",
      "version": "2.4.0"
    },
    "ownerReferences": [
      {
        "apiVersion": "v1",
        "kind": "Pod",
        "name": "es-driver",
        "uid": "670f0971-4139-11e9-bdbe-42010a8000bb",
        "controller": true
      }
    ]
  },
  "spec": {
    "volumes": [
      {
        "name": "spark-local-dir-1",
        "emptyDir": {}
      },
      {
        "name": "default-token-8wjq8",
        "secret": {
          "secretName": "default-token-8wjq8",
          "defaultMode": 420
        }
      }
    ],
    "containers": [
      {
        "name": "executor",
        "image": "gcr.io/equity-ai/metric-pipeline-spark:47",
        "args": [
          "executor"
        ],
        "ports": [
          {
            "name": "blockmanager",
            "containerPort": 7079,
            "protocol": "TCP"
          }
        ],
        "env": [
          {
            "name": "SPARK_DRIVER_URL",
            "value": "spark://CoarseGrainedScheduler@es-1552005039106-driver-svc.default.svc:7078"
          },
          {
            "name": "SPARK_EXECUTOR_CORES",
            "value": "1"
          },
          {
            "name": "SPARK_EXECUTOR_MEMORY",
            "value": "800m"
          },
          {
            "name": "SPARK_APPLICATION_ID",
            "value": "spark-application-1552005275761"
          },
          {
            "name": "SPARK_CONF_DIR",
            "value": "/opt/spark/conf"
          },
          {
            "name": "SPARK_EXECUTOR_ID",
            "value": "1"
          },
          {
            "name": "SPARK_EXECUTOR_POD_IP",
            "valueFrom": {
              "fieldRef": {
                "apiVersion": "v1",
                "fieldPath": "status.podIP"
              }
            }
          },
          {
            "name": "SPARK_LOCAL_DIRS",
            "value": "/var/data/spark-609fd0f6-8f41-4e49-806e-12da97b76099"
          }
        ],
        "resources": {
          "limits": {
            "memory": "1184Mi"
          },
          "requests": {
            "cpu": "1",
            "memory": "1184Mi"
          }
        },
        "volumeMounts": [
          {
            "name": "spark-local-dir-1",
            "mountPath": "/var/data/spark-609fd0f6-8f41-4e49-806e-12da97b76099"
          },
          {
            "name": "default-token-8wjq8",
            "readOnly": true,
            "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
          }
        ],
        "terminationMessagePath": "/dev/termination-log",
        "terminationMessagePolicy": "File",
        "imagePullPolicy": "Always"
      }
    ],
    "restartPolicy": "Never",
    "terminationGracePeriodSeconds": 30,
    "dnsPolicy": "ClusterFirst",
    "nodeSelector": {
      "node-type": "high-cpu"
    },
    "serviceAccountName": "default",
    "serviceAccount": "default",
    "nodeName": "gke-ai-k8s-cluster-high-cpu2-df825d05-46f9",
    "securityContext": {},
    "hostname": "es-1552005039106-exec-1",
    "schedulerName": "default-scheduler",
    "tolerations": [
      {
        "key": "node.kubernetes.io/not-ready",
        "operator": "Exists",
        "effect": "NoExecute",
        "tolerationSeconds": 300
      },
      {
        "key": "node.kubernetes.io/unreachable",
        "operator": "Exists",
        "effect": "NoExecute",
        "tolerationSeconds": 300
      }
    ],
    "priority": 0
  },
  "status": {
    "phase": "Running",
    "conditions": [
      {
        "type": "Initialized",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2019-03-08T00:34:36Z"
      },
      {
        "type": "Ready",
        "status": "False",
        "lastProbeTime": null,
        "lastTransitionTime": "2019-03-08T00:34:37Z"
      },
      {
        "type": "ContainersReady",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": null
      },
      {
        "type": "PodScheduled",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2019-03-08T00:34:36Z"
      }
    ],
    "hostIP": "10.128.0.29",
    "podIP": "10.40.78.5",
    "startTime": "2019-03-08T00:34:36Z",
    "containerStatuses": [
      {
        "name": "executor",
        "state": {
          "running": {
            "startedAt": "2019-03-08T00:34:37Z"
          }
        },
        "lastState": {},
        "ready": true,
        "restartCount": 0,
        "image": "gcr.io/equity-ai/metric-pipeline-spark:47",
        "imageID": "docker-pullable://gcr.io/equity-ai/metric-pipeline-spark@sha256:6fa0d3621c79ad2bcac92b320e9355b5d5126c5c5d14b72e85b87cd5200338e4",
        "containerID": "docker://80b97c7aec27991bbd1e32d28ad1dc14cfb45014512a5d52765e22fb3ee06c3b"
      }
    ],
    "qosClass": "Burstable"
  }
}
```
Kindly help to investigate this.
Thanks
