### ISSUE TITLE
Unable to set the masterURL for the horovod-spark on k8s

### ISSUE THREAD

**Issue by mohanraj1311** [GoogleCloudPlatform/spark-on-k8s-operator#456]
i was trying to run simple MNIST spark app on k8s cluster , i face the following error:
```
py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: org.apache.spark.SparkException: Could not parse Master URL: '<pyspark.conf.SparkConf object at 0x7fdb4b984be0>'
        at org.apache.spark.SparkContext$.org$apache$spark$SparkContext$$createTaskScheduler(SparkContext.scala:2784)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:493)
        at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
```

I set the master URL like this : 

```
# Create a spark session for training the model
conf = SparkConf().setAppName('training')
conf.setMaster('k8s://http://localhost:8080')
sc = SparkContext(conf)

```

The full program I used : 

```
from __future__ import print_function
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.preprocessing.image import ImageDataGenerator
from keras import backend as K
import tensorflow as tf
import horovod.keras as hvd
import horovod.spark
from pyspark import SparkConf
from pyspark import SparkContext


def training_fn():
    # Horovod: initialize Horovod.
    hvd.init()

    # Horovod: pin GPU to be used to process local rank (one GPU per process)
    config = tf.ConfigProto()
    # Commenting the config_gpu settings as i run on CPU
    # config.gpu_options.allow_growth = True
    # config.gpu_options.visible_device_list = str(hvd.local_rank())
    K.set_session(tf.Session(config=config))

    batch_size = 128
    num_classes = 10

    # Enough epochs to demonstrate learning rate warmup and the reduction of
    # learning rate when training plateaues.
    epochs = 24

    # Input image dimensions
    img_rows, img_cols = 28, 28

    # The data, shuffled and split between train and test sets
    (x_train, y_train), (x_test, y_test) = mnist.load_data()

    # Determine how many batches are there in train and test sets
    train_batches = len(x_train) // batch_size
    test_batches = len(x_test) // batch_size

    if K.image_data_format() == 'channels_first':
        x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
        x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
        input_shape = (1, img_rows, img_cols)
    else:
        x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
        x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
        input_shape = (img_rows, img_cols, 1)

    x_train = x_train.astype('float32')
    x_test = x_test.astype('float32')
    x_train /= 255
    x_test /= 255
    print('x_train shape:', x_train.shape)
    print(x_train.shape[0], 'train samples')
    print(x_test.shape[0], 'test samples')

    # Convert class vectors to binary class matrices
    y_train = keras.utils.to_categorical(y_train, num_classes)
    y_test = keras.utils.to_categorical(y_test, num_classes)

    model = Sequential()
    model.add(Conv2D(32, kernel_size=(3, 3),
                     activation='relu',
                     input_shape=input_shape))
    model.add(Conv2D(64, (3, 3), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.25))
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(num_classes, activation='softmax'))

    # Horovod: adjust learning rate based on number of GPUs.
    opt = keras.optimizers.Adadelta(lr=1.0 * hvd.size())

    # Horovod: add Horovod Distributed Optimizer.
    opt = hvd.DistributedOptimizer(opt)

    model.compile(loss=keras.losses.categorical_crossentropy,
                  optimizer=opt,
                  metrics=['accuracy'])

    callbacks = [
        # Horovod: broadcast initial variable states from rank 0 to all other processes.
        # This is necessary to ensure consistent initialization of all workers when
        # training is started with random weights or restored from a checkpoint.
        hvd.callbacks.BroadcastGlobalVariablesCallback(0),

        # Horovod: average metrics among workers at the end of every epoch.
        #
        # Note: This callback must be in the list before the ReduceLROnPlateau,
        # TensorBoard or other metrics-based callbacks.
        hvd.callbacks.MetricAverageCallback(),

        # Horovod: using `lr = 1.0 * hvd.size()` from the very beginning leads to worse final
        # accuracy. Scale the learning rate `lr = 1.0` ---> `lr = 1.0 * hvd.size()` during
        # the first five epochs. See https://arxiv.org/abs/1706.02677 for details.
        hvd.callbacks.LearningRateWarmupCallback(warmup_epochs=5, verbose=1),

        # Reduce the learning rate if training plateaues.
        keras.callbacks.ReduceLROnPlateau(patience=10, verbose=1),
    ]

    # Horovod: save checkpoints only on worker 0 to prevent other workers from corrupting them.
    if hvd.rank() == 0:
        callbacks.append(keras.callbacks.ModelCheckpoint('./checkpoint-{epoch}.h5'))

    # Set up ImageDataGenerators to do data augmentation for the training images.
    train_gen = ImageDataGenerator(rotation_range=8, width_shift_range=0.08, shear_range=0.3,
                                   height_shift_range=0.08, zoom_range=0.08)
    test_gen = ImageDataGenerator()

    # Train the model.
    # Horovod: the training will randomly sample 1 / N batches of training data and
    # 3 / N batches of validation data on every worker, where N is the number of workers.
    # Over-sampling of validation data helps to increase probability that every validation
    # example will be evaluated.
    model.fit_generator(train_gen.flow(x_train, y_train, batch_size=batch_size),
                        steps_per_epoch=train_batches // hvd.size(),
                        callbacks=callbacks,
                        epochs=epochs,
                        verbose=1,
                        validation_data=test_gen.flow(x_test, y_test, batch_size=batch_size),
                        validation_steps=3 * test_batches // hvd.size())
    return model, x_test, y_test


# Create a spark session for training the model
conf = SparkConf().setAppName('training')
conf.setMaster('k8s://http://localhost:8080')
sc = SparkContext(conf)


tr_model, test_data_x_test, test_data_y_test = horovod.spark.run((training_fn), num_proc=3, verbose=2)


# Evaluate the model on the full data set.
score = tr_model.evaluate(test_data_x_test, test_data_y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

sc.stop()

```

**Comment by liyinan926** [comment]
Looks like you are not using the spark operator to run this. This is a client mode PySpark job, and the error seems to suggest that the k8s url was not recognized. You might want to post this question to the Spark user mailing list instead of here.

**Comment by mohanraj1311** [comment]
@liyinan926 : Hi, I am using the operator. Below is my operation file.
```
apiVersion: "sparkoperator.k8s.io/v1beta1"
 kind: SparkApplication
 metadata:
   name: keras-mnist-spark-horo
   namespace: hdfs1
 spec:
   type: Python
   pythonVersion: "3"
   mode: cluster
   image: "spark-tf-keras-horo-pytorch13:latest"
   imagePullPolicy: Never
   mainApplicationFile: https://raw.githubusercontent.com/mohanraj1311/horovod-spark-tf-example/master/keras_mnist_spark_horo.py
   sparkVersion: "2.4.0"
   hadoopConfigMap: hdfs-1-config
   restartPolicy:
     type: Never
   volumes:
     - name: "test-volume"
       hostPath:
         path: "/tmp"
         type: Directory
   driver:
     cores: 0.1
     coreLimit: "200m"
     memory: "1024m"
     labels:
       version: 2.4.0
     serviceAccount: spark
     volumeMounts:
       - name: "test-volume"
         mountPath: "/tmp"
   executor:
     cores: 1
     instances: 1
     memory: "1024m"
     labels:
       version: 2.4.0
     volumeMounts:
       - name: "test-volume"
         mountPath: "/tmp"
```

**Comment by liyinan926** [comment]
The operator only works with the cluster mode. That means your PySpark job needs to run in the cluster mode to be launched using the operator. With the cluster mode, you should not need to set the master URL.

**Comment by mohanraj1311** [comment]
ok, i modified the code by commenting the setMaster part as you said . Now its :
```
# Create a spark session for training the model
conf = SparkConf().setAppName('training')
#conf.setMaster('k8s://http://localhost:6443')
sc = SparkContext(conf)


tr_model, test_data_x_test, test_data_y_test = horovod.spark.run((training_fn), num_proc=3, verbose=2)


# Evaluate the model on the full data set.
score = tr_model.evaluate(test_data_x_test, test_data_y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

sc.stop()
```
The error is still the same :
 ```
2019-03-28 17:23:43 INFO  SparkContext:54 - Successfully stopped SparkContext
Traceback (most recent call last):
  File "/tmp/spark-70921cb7-b694-4c5e-9421-1d88c90c328e/keras_mnist_spark_horo.py", line 135, in <module>
    sc = SparkContext(conf)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/context.py", line 118, in __init__
  File "/opt/spark/python/lib/pyspark.zip/pyspark/context.py", line 180, in _do_init
  File "/opt/spark/python/lib/pyspark.zip/pyspark/context.py", line 288, in _initialize_context
  File "/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1525, in __call__
  File "/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: org.apache.spark.SparkException: Could not parse Master URL: '<pyspark.conf.SparkConf object at 0x7f3a8f072b70>'
        at org.apache.spark.SparkContext$.org$apache$spark$SparkContext$$createTaskScheduler(SparkContext.scala:2784)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:493)
        at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:238)
        at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
        at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by liyinan926** [comment]
Are you using a Spark image with the Kubernetes mode enabled?

**Comment by mohanraj1311** [comment]
@liyinan926 : Hi, i am not exactly getting your question. I am submitting a spark job using the spark operator, the version of spark here is 2.4

**Comment by liyinan926** [comment]
I meant the image `spark-tf-keras-horo-pytorch13:latest`. Is this image built from a Spark dist with the k8s mode enabled?

**Comment by mohanraj1311** [comment]
yes, i am able to submit a spark job to the same cluster using the same image. 
The spark job i used was written in scala though : 

```
 apiVersion: "sparkoperator.k8s.io/v1beta1"
 kind: SparkApplication
 metadata:
   name: spark-apache-logs
   namespace: hdfs1
 spec:
   type: Scala
   mode: cluster
   image: "spark-tf-keras-horo-pytorch13:latest"
   imagePullPolicy: Never
   mainClass: ApacheLogAnalysis
   mainApplicationFile: https://github.com/mohanraj1311/ApacheLogAnalysisJar/raw/master/analysisofapachelogs_2.11-0.1.jar
   arguments:
       - hdfs://hdfs-1-namenode-1.hdfs-1-namenode.hdfs1.svc.cluster.local:8020/data/apache-logs
   hadoopConfigMap: hdfs-1-config
   restartPolicy:
     type: Never
   volumes:
     - name: "test-volume"
       hostPath:
         path: "/tmp"
         type: Directory
   driver:
     cores: 0.1
     coreLimit: "200m"
     memory: "1024m"
     labels:
       version: 2.4.0
     serviceAccount: spark
     volumeMounts:
       - name: "test-volume"
         mountPath: "/tmp"
   executor:
     cores: 1
     instances: 1
     memory: "512m"
     labels:
       version: 2.4.0
     volumeMounts:
       - name: "test-volume"
         mountPath: "/tmp"

```
