### ISSUE TITLE
Unable to specify scheduler name when submitting spark application

### ISSUE THREAD

**Issue by TommyLike** [GoogleCloudPlatform/spark-on-k8s-operator#463]
We are using spark operator to execute task in cluster, at the meantime we have deployed another custom scheduler which is used to enhance the scheduling case for HPC [Kube batch](https://github.com/kubernetes-sigs/kube-batch), Need Spark operator supporting specifying scheduler name for task pods. For example:
```
apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v2.4.0"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.11-2.4.0.jar"
  sparkVersion: "2.4.0"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    schedulerName: "kube-batch"
    cores: 0.1
    coreLimit: "200m"
    memory: "512m"
    labels:
      version: 2.4.0
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    schedulerName: "kube-batch"
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.0
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
```
