### ISSUE TITLE
Support for multiple namespaces

### ISSUE THREAD

**Issue by skonto** [GoogleCloudPlatform/spark-on-k8s-operator#507]
There is an implementation of a multi-watcher mentioned here: https://github.com/kubernetes/kubernetes/issues/74415#issuecomment-497570002
We could utilize that.

**Comment by skonto** [comment]
@liyinan926 what do you think moving to controller-runtime (kubebuilder), it is more uptodate https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/cache/multi_namespace_cache.go

**Comment by liyinan926** [comment]
It would be great to move to using controller-runtime. But it looks like possible to just use that particular package without doing a huge round of refactoring.

**Comment by skonto** [comment]
@liyinan926 I understand do you have any insight as what the future might be controller-runtime vs the client lib thing. Long term what should we support?

**Comment by liyinan926** [comment]
Long term controller-runtime is the way to go I think.

**Comment by doctapp** [comment]
Any way of deploying multiple spark operators on k8s, like one per namespace?

**Comment by zzvara** [comment]
I deploy multiple Spark Operators using:

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: spark-operator
  namespace: production
spec:
  chart:
    repository: https://googlecloudplatform.github.io/spark-on-k8s-operator
    name: sparkoperator
    version: 1.0.5
  releaseName: spark-operator
  values:
    webhook:
      enabled: true
    resyncInterval: 5
    metrics:
      enable: false
    controllerThreads: 2
    batchScheduler:
      enable: true
```

and then I have one `HelmRelease` for each namespace.
