### ISSUE TITLE
Specifying driver and executor pod properties

### ISSUE THREAD

**Issue by foxish** [GoogleCloudPlatform/spark-on-k8s-operator#52]
Starting a couple of discussions around specification of properties.

```
spec:
  deps: {}
  driver:
    cores: "0.1"
    image: liyinan926/spark-driver:v2.3.0
  executor:
    image: liyinan926/spark-executor:v2.3.0
    instances: 1
    memory: 512m
``` 

Should this mimic the driver/executor properties more closely?
For example: `spark.kubernetes.driver.limit.cores`. 

/xref: https://dist.apache.org/repos/dist/dev/spark/v2.3.0-rc2-docs/_site/running-on-kubernetes.html
