### ISSUE TITLE
Long Python jobs that read/write from S3 does not get completed

### ISSUE THREAD

**Issue by jvaesteves** [GoogleCloudPlatform/spark-on-k8s-operator#534]
I have being testing the operator for some of my three-hours-long spark jobs. They are all written in Python and read from/write to a S3 bucket, and take an average of 100 minutes to successfully complete. But, even after successfully persisting the result on the destination bucket, the job takes something between 3 and 4 hours to change the pod status to completed. Here is a logs example.

```
19/06/26 17:08:55 INFO TaskSchedulerImpl: Removed TaskSet 1.0, whose tasks have all completed, from pool
19/06/26 17:08:55 INFO DAGScheduler: ResultStage 1 (orc at NativeMethodAccessorImpl.java:0) finished in 5951.363 s
19/06/26 17:08:55 INFO DAGScheduler: Job 1 finished: orc at NativeMethodAccessorImpl.java:0, took 5951.408878 s
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 49
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 39
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 41
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 48
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 62
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 58
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 61
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 44
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 42
19/06/26 17:28:46 INFO BlockManagerInfo: Removed broadcast_2_piece0 on test-1561562919215-driver-svc.spark.svc:7079 in memory (size: 882.0 KB, free: 413.9 MB)
19/06/26 17:28:46 INFO BlockManagerInfo: Removed broadcast_2_piece0 on 10.130.30.32:34871 in memory (size: 882.0 KB, free: 4.4 GB)
19/06/26 17:28:46 INFO BlockManagerInfo: Removed broadcast_2_piece0 on 10.130.30.164:35545 in memory (size: 882.0 KB, free: 4.4 GB)
19/06/26 17:28:46 INFO BlockManagerInfo: Removed broadcast_2_piece0 on 10.130.10.240:39571 in memory (size: 882.0 KB, free: 4.4 GB)
19/06/26 17:28:46 INFO BlockManagerInfo: Removed broadcast_2_piece0 on 10.130.10.143:41829 in memory (size: 882.0 KB, free: 4.4 GB)
19/06/26 17:28:46 INFO BlockManagerInfo: Removed broadcast_2_piece0 on 10.130.30.96:45027 in memory (size: 882.0 KB, free: 4.4 GB)
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 43
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 47
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 51
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 57
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 50
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 60
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 52
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 55
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 40
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 46
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 54
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 53
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 56
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 59
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 45
19/06/26 17:28:46 INFO ContextCleaner: Cleaned accumulator 38
19/06/26 21:10:27 INFO FileFormatWriter: Write Job dde4f5e9-90f6-4010-aa84-52571403e388 committed.
19/06/26 21:10:27 INFO FileFormatWriter: Finished processing stats for write job dde4f5e9-90f6-4010-aa84-52571403e388.
19/06/26 21:10:27 INFO SparkUI: Stopped Spark web UI at http://test-1561562919215-driver-svc.spark.svc:4040
19/06/26 21:10:27 INFO KubernetesClusterSchedulerBackend: Shutting down all executors
19/06/26 21:10:27 INFO KubernetesClusterSchedulerBackend$KubernetesDriverEndpoint: Asking each executor to shut down
19/06/26 21:10:27 WARN ExecutorPodsWatchSnapshotSource: Kubernetes client has been closed (this is expected if the application is shutting down.)
19/06/26 21:10:27 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
19/06/26 21:10:27 INFO MemoryStore: MemoryStore cleared
19/06/26 21:10:27 INFO BlockManager: BlockManager stopped
19/06/26 21:10:27 INFO BlockManagerMaster: BlockManagerMaster stopped
19/06/26 21:10:27 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
19/06/26 21:10:27 INFO SparkContext: Successfully stopped SparkContext
19/06/26 21:10:27 INFO ShutdownHookManager: Shutdown hook called
19/06/26 21:10:27 INFO ShutdownHookManager: Deleting directory /var/data/spark-e71606ee-363b-4e9e-b8f3-a36fc2341671/spark-7534a7b9-11e3-4cce-835f-2db2f704eec8/pyspark-19c36085-fe76-49c1-9cd2-08043206bcb5
19/06/26 21:10:27 INFO ShutdownHookManager: Deleting directory /var/data/spark-e71606ee-363b-4e9e-b8f3-a36fc2341671/spark-7534a7b9-11e3-4cce-835f-2db2f704eec8
19/06/26 21:10:27 INFO ShutdownHookManager: Deleting directory /tmp/spark-d782349f-5398-43df-a724-8a73fd1d2daa
```

And here is my SparkApplication definition.

```yaml
apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: test
  namespace: spark
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: <image based on apache/spark 2.4.3 Dockerfile including AWS s3 dependencies>
  imagePullPolicy: Always
  mainApplicationFile: <s3-bucket-location>
  sparkVersion: "2.4.3"
  hadoopConf:
    "fs.s3.awsAccessKeyId": "<access-key>"
    "fs.s3.awsSecretAccessKey": "<secret-key>"
    "fs.s3.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "fs.s3n.awsAccessKeyId": "<access-key>"
    "fs.s3n.awsSecretAccessKey": "<secret-key>"
    "fs.s3n.impl": "org.apache.hadoop.fs.s3native.NativeS3FileSystem"
    "fs.s3a.access.key": "<access-key>"
    "fs.s3a.secret.key": "<secret-key>"
    "fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
  restartPolicy:
    type: Never
  driver:
    cores: 0.1
    memory: "1G"
    labels:
      version: 2.4.3
    serviceAccount: <service-account>
  executor:
    cores: 2
    instances: 5
    memory: "8G"
    labels:
      version: 2.4.3
```
