### ISSUE TITLE
Sidecar container does not show up

### ISSUE THREAD

**Issue by kpulipati** [GoogleCloudPlatform/spark-on-k8s-operator#558]
I am trying to spin up a sidecar container in my driver pod and I followed the docs. But somehow the side car container is not spinning up and I am struggling to understand why. However my driver and executor pods starts just fine,Here is how my manifest file look like, can anyone please help me with this and let me know if I am missing anything?:

```

apiVersion: sparkoperator.k8s.io/v1beta1
kind: SparkApplication
metadata:
 name: spark-sidecar-test1
 namespace: engine-memory
spec:
 type: Scala
 cluster: local
 image: 8982399892389.dkr.ecr.us-west-2.amazonaws.com/spark-image:latest
 imagePullPolicy: Always
 mainClass: com.sparktest.example
 mainApplicationFile: local:///example/jars/etl-1.0-SNAPSHOT-jar-with-dependencies.jar
 driver:
   serviceAccount: spark-service-account
   sidecars:
   - name: "count1"
     image: "busybox"
     args: [/bin/sh, -c,
            'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']
 sparkConf:
   spark.shuffle.io.maxRetries: "0"
   spark.port.maxRetries: "0"
   spark.rpc.numRetries: "0"
   spark.task.maxFailures: "0"
   spark.stage.maxConsecutiveAttempts: "0"
 arguments:
 - "size1k"
 - "test"
 - "100000"
```
