### ISSUE TITLE
Executors use the default service account instead of the Driver's service account

### ISSUE THREAD

**Issue by doctapp** [GoogleCloudPlatform/spark-on-k8s-operator#596]
Currently, if I want executors to pull using a secret, the secret needs to be part of the `default` service account under the namespace of the Spark application even if we specify `serviceAccount` on the DriverSpec.

Either the executors should use the Driver's serviceAccount (`DriverSpec`) or there should be a way of specifying it on the `ExecutorSpec`.

Any thoughts?

Thanks

**Comment by liyinan926** [comment]
Have you tried `spec.imagePullSecrets`? Secrets specified here get applied to both the driver and executor pods.

**Comment by doctapp** [comment]
Yes, that's how I set it. When I do this, my driver starts but the
executers block on trying to pull the image.

**Comment by liyinan926** [comment]
That's interesting. Have you checked the executor pods to see if they do have the image pull secrets?

**Comment by doctapp** [comment]
Can't check this now, but as soon as I add the secret to default in the
app's namespace the pull works.

**Comment by liyinan926** [comment]
When you get a chance, can you also paste here an example of how you set `imagePullSecrets`?

**Comment by doctapp** [comment]
I can't seem to reproduce it now even if I remove the imagePullSecret from
the default sa under spark-operator. I tried publishing a new image and the
executors can still pull it. We're running a bare metal cluster which
wasn't allowed to pull until I added the secret to the default sa for the
executors.

Any idea why it works now as I've seen it consistently behave the way I
described (all sa under the spark-operator namespace have an empty
imagePullSecrets)?

Here's the yaml for my sample app which only worked when I added mysecret
to default sa under spark-operator:
```
apiVersion: sparkoperator.k8s.io/v1beta1
kind: SparkApplication
metadata:
  name: myapp
  namespace: spark-operator
spec:
  type: Scala
  mode: cluster
  image: myreg.com/myns/myimage:v0.0.1
  imagePullPolicy: Always
  imagePullSecrets:
  - mysecret
  mainClass: myclass
  mainApplicationFile: local:///my.jar
  sparkVersion: 2.4.0
  driver:
    cores: 1
    memory: 10m
    labels:
      version: 2.4.0
    serviceAccount: spark-operator-spark
  executor:
    cores: 1
    instances: 3
    memory: 10m
    labels:
      version: 2.4.0
```
