### ISSUE TITLE
What I am doing wrong

### ISSUE THREAD

**Issue by kodelint** [GoogleCloudPlatform/spark-on-k8s-operator#639]
I am trying to run a `Pyspark` application using operator. I can run it perfectly if I backed the `python` application in `spark` image but when I am trying to get them from `s3`, I am getting into all sort issue. Please advise what I am doing wrong:

Here is my `YAML` File
```
apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: generic-pyspark2.4.4
  namespace: random
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: 'pyspark-2.4.4-hadoop-2.7:v0.1"
  imagePullPolicy: Always
  class: org.apache.spark.deploy.PythonRunner
  mainApplicationFile: "s3a://buckets/pyspark/model.py"
  sparkConf:
    "spark.hadoop.fs.s3a.aws.credentials.provider": com.amazonaws.auth.InstanceProfileCredentialsProvider
    "spark.hadoop.fs.s3a.impl": org.apache.hadoop.fs.s3a.S3AFileSystem
    "spark.shuffle.service.enabled": false
    "spark.speculation": false
  deps:
    pyFiles:
      - "s3a://buckets/pyspark/aws_utils.py"
      - "s3a://buckets/pyspark/dataset.py"
  sparkVersion: "2.4.4"
  driver:
    cores: 2
    # coreLimit: "1200m"
    memory: "1024m"
    labels:
      version: 2.4.4
    serviceAccount: sparkoperator
  executor:
    cores: 4
    instances: 5
    memory: "10240m"
    labels:
      version: 2.4.4
```

I am using 

- `spark` - 2.4.4
- `aws-java-sdk-1.7.3.jar`
- `hadoop-aws-2.7.3.jar`
- `scala`: 2.11

**Comment by kodelint** [comment]
I always get the error:

```
19/09/26 01:22:40 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Traceback (most recent call last):
  File "/tmp/spark-de1303c8-6a8d-47d7-bbd1-23f953fd03a6/model.py", line 1, in <module>
    from aws_utils import *
ModuleNotFoundError: No module named 'aws_utils'
```
Which mean it is not able to locate the dependent files

**Comment by liyinan926** [comment]
Please check out https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/404.

**Comment by kodelint** [comment]
@liyinan926 I already have the `jars` in the image. Here is my `Dockerfile`

```
FROM gcr.io/spark-operator/spark-py:v2.4.4
ENV PYTHONPATH "$SPARK_HOME/python/:$SPARK_HOME/python/lib/py4j-0.10.4-src.zip:$PYTHONPATH"
ENV PYSPARK_PYTHON "python3"
RUN rm -f /usr/bin/python && ln -s /usr/bin/python3 /usr/bin/python
RUN  apk update \
     && apk add make automake gcc g++ subversion python3-dev
RUN  pip3.6 install Pathlib numpy pandas==0.24.2 boto3
COPY jars/* /opt/spark/jars/
```
and the `jars` folder has following:

```
>> ls -l jars/ | awk '{print $9}'
aws-java-sdk-1.7.3.jar
hadoop-aws-2.7.3.jar
```

**Comment by kodelint** [comment]
Thanks for pointer @liyinan926 Now this is what I have.

Spark Operator Image `Dockerfile`:
```
FROM gcr.io/spark-operator/spark-operator:v2.4.0-v1beta1-0.8.2

ADD http://central.maven.org/maven2/org/apache/hadoop/hadoop-aws/2.7.3/hadoop-aws-2.7.3.jar $SPARK_HOME/jars
ADD http://central.maven.org/maven2/com/amazonaws/aws-java-sdk/1.7.4/aws-java-sdk-1.7.4.jar $SPARK_HOME/jars
```
Spark Driver and Executer Image `Dockerfile`:
```
FROM gcr.io/spark-operator/spark-py:v2.4.4
ADD http://central.maven.org/maven2/org/apache/hadoop/hadoop-aws/2.7.3/hadoop-aws-2.7.3.jar $SPARK_HOME/jars
ADD http://central.maven.org/maven2/com/amazonaws/aws-java-sdk/1.7.4/aws-java-sdk-1.7.4.jar $SPARK_HOME/jars
ENV PYTHONPATH "$SPARK_HOME/python/:$SPARK_HOME/python/lib/py4j-0.10.4-src.zip:$PYTHONPATH"
ENV PYSPARK_PYTHON "python3"
RUN rm -f /usr/bin/python && ln -s /usr/bin/python3 /usr/bin/python
RUN  apk update \
     && apk add make automake gcc g++ subversion python3-dev
RUN  pip3.6 install Pathlib numpy pandas==0.24.2 boto3
```

and my `YAML`
```
apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: generic-pyspark2.4.4
  namespace: random
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: 'pyspark-2.4.4-hadoop-2.7:v0.1"
  imagePullPolicy: Always
  class: org.apache.spark.deploy.PythonRunner
  mainApplicationFile: "s3a://buckets/pyspark/model.py"
  sparkConf:
    "spark.hadoop.fs.s3a.aws.credentials.provider": com.amazonaws.auth.InstanceProfileCredentialsProvider
    "spark.hadoop.fs.s3a.impl": org.apache.hadoop.fs.s3a.S3AFileSystem
    "spark.shuffle.service.enabled": false
    "spark.speculation": false
  deps:
    pyFiles:
      - "s3a://buckets/pyspark/preprocess.zip"
  sparkVersion: "2.4.4"
  driver:
    cores: 2
    # coreLimit: "1200m"
    memory: "1024m"
    labels:
      version: 2.4.4
    serviceAccount: sparkoperator
  executor:
    cores: 4
    instances: 5
    memory: "10240m"
    labels:
      version: 2.4.4
```

I also added the following to my main `PySpark` Application `model.py`:

```
dep_file_path = pyspark.SparkFiles.get("sensei-preprocess.zip")
# Init Single Spark Context and Wrap with SQLContext for monkey patches
LOG.info("Initializing Spark Context")
sc = SparkContext.addPyFile(dep_file_path)
sc = SparkContext(appName="preprocessor")
sqlContext = SQLContext(sc)
sqlContext.sql("set spark.sql.caseSensitive=true")
sc._conf.set("spark.shuffle.service.enabled", "false")
sc._conf.set("spark.dynamicAllocation.enabled" , "false")
sc._conf.set("spark.hadoop.fs.s3a.fast.upload", "true")
sc._conf.set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
sc._conf.set("spark.debug.maxToStringFields", "500")
print("Spark Context Configs:\n")
print(sc._conf.getAll())
```
