### ISSUE TITLE
Validation failure: type in spec.volumes.configMap is required

### ISSUE THREAD

**Issue by NanXuejiao** [GoogleCloudPlatform/spark-on-k8s-operator#736]
I get this error when use confimap.`validation failure list: type in spec.volumes.configMap is required`

It seems like needing `type` under configMap, but what's `type` mean?  I read docs but get nothing about how to config `type`.

I want to use configmap to set `spec.arguments` flexibly, instead of specify a config file in image.

Following is part of yaml file.
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: test-sparkapplication
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "test:v1.1"
  imagePullPolicy: IfNotPresent
  mainClass: com.test.TestLog
  mainApplicationFile: "local:///opt/spark/lib/Test.jar"
  arguments:
  - "/opt/spark/lib/test.conf"
  deps:
    jars:
      - local:///opt/spark/lib/kafka_2.11-0.8.2.1.jar
      - ......
  sparkVersion: "2.4.3"
  restartPolicy:
    type: Always
  volumes:
    - name: "config-arg"
      configMap:
        name: test-conf
        items:
          - key: test.conf
            path: test.conf
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 2.4.3
    serviceAccount: spark
    volumeMounts:
      - name: "config-arg"
        mountPath: /opt/spark/lib
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.3
    volumeMounts:
      - name: "config-arg"
        mountPath: /opt/spark/lib
---
apiVersion: v1
data:
  test.conf: |+
    batch.duration=10
    .....
kind: ConfigMap
metadata:
  name: test-conf
  namespace: default

  ```

---

**Comment by liyinan926** [comment]
This seems relevant: https://github.com/kubernetes-sigs/kubefed/issues/469.

**Comment by liyinan926** [comment]
A workaround is to delete the appearances of the following in manifest/crds/sparkoperator.k8s.io_sparkapplications.yaml.

```
                configMaps:
                  items:
                    properties:
                      name:
                        type: string
                      path:
                        type: string
                    required:
                    - name
                    - path
                    type: object
                  type: array
```
