### ISSUE TITLE
Mounting local scratch dir conflicts with default directory

### ISSUE THREAD

**Issue by sb2nov** [GoogleCloudPlatform/spark-on-k8s-operator#770]
Running a volume named `spark-local-dir-1` creates a duplicate volume exception 

```
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure 
executing: POST at: https://10.100.0.1/api/v1/namespaces/datainfra/pods. Message: Pod "job-
driver" is invalid: spec.volumes[3].name: Duplicate value: "spark-local-dir-1". Received status: 
Status(apiVersion=v1, code=422, details=StatusDetails(causes=
[StatusCause(field=spec.volumes[3].name, message=Duplicate value: "spark-local-dir-1", 
reason=FieldValueDuplicate, additionalProperties={})], group=null, kind=Pod, name=cue-news-
job-driver, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Pod 
"job-driver" is invalid: spec.volumes[3].name: Duplicate value: "spark-local-dir-1", 
metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), 
reason=Invalid, status=Failure, additionalProperties={}).
```

**Comment by sb2nov** [comment]
```
  driver:
    cores: 1
    memory: 1024m
    serviceAccount: spark
    volumeMounts:
      - name: spark-local-dir-1
        mountPath: /mnt/spark/work
  executor:
    cores: 1
    instances: 8
    memory: 4096m
    volumeMounts:
      - name: spark-local-dir-1
        mountPath: /mnt/spark/work
  volumes:
    - name: spark-local-dir-1
      emptyDir: {}
```
