### ISSUE TITLE
[Issue] Failed to pull image from IBM Cloud by sparkoperator with "unexpected status: 401 Unauthorized"

### ISSUE THREAD

**Issue by mstiunicon** [GoogleCloudPlatform/spark-on-k8s-operator#773]
Summary:
Failed to pull image from IBM Cloud by sparkoperator, but can successfully pull the image without sparkoperator

Steps:
0) install sparkoperator:
```
kubectl create serviceaccount spark 
kubectl create clusterrolebinding xxxx-cluster-admin-binding --clusterrole=cluster-admin --user=xxxx@cn.ibm.com
kubectl create clusterrolebinding spark-role --clusterrole=edit --serviceaccount=default:spark --namespace=default
kubectl create namespace spark-operator
helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator
helm install incubator/sparkoperator --namespace spark-operator --set sparkJobNamespace=default --set enableWebhook=true --skip-crds --generate-name
```
1) pull the image with sparkoperator
spark-py-feeder.yaml
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-feeder
  namespace: default
spec:
  logLevel: 3
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: us.icr.io/metering-k8s/meteringfeeder:latest
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/metering_feeder/src/main.py  
  sparkVersion: "2.4.4"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 2.4.4
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.4
```
after run command "kubectl apply -f spark-py-feeder.yaml"
Errors:  Failed to pull image "us.icr.io/metering-k8s/meteringfeeder:latest": rpc error: code = Unknown desc = failed to pull and unpack image "us.icr.io/metering-k8s/meteringfeeder:latest": failed to resolve reference "us.icr.io/metering-k8s/meteringfeeder:latest": failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized

![Snap71](https://user-images.githubusercontent.com/17581823/72535527-a6628f80-38b3-11ea-9684-b440feb23d04.jpg)

2) pull the image without sparkoperator
feeder_test.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: feeder-test
  labels:
    component: web
spec:
  containers:
    - name: client
      image: us.icr.io/metering-k8s/meteringfeeder:latest
      ports:
        - containerPort: 3000
```

after run command "kubectl apply -f feeder_test.yaml"
the same image pulled successfully.
![Snap72](https://user-images.githubusercontent.com/17581823/72535760-0bb68080-38b4-11ea-8529-e8a7c900a347.jpg)

Maybe there are some options I missed?
