### ISSUE TITLE
Support for envFrom to set environment variables from a configmap

### ISSUE THREAD

**Issue by jkleckner** [GoogleCloudPlatform/spark-on-k8s-operator#785]
Many tools permit using `envFrom` to set environment variables from a `ConfigMap` or possibly from a `Secret` instead of mounting into the filesystem.

It would be nice for both `CRD` definitions to allow this in the specification.

See for example:
* https://github.com/apache/airflow/pull/4952

Related issues: #694 , #216 

This has been mentioned a couple of times in the slack channel but I thought it would be good to discuss here whether it makes sense.  Slack channel discussions do not show up in web searches...

**Comment by liyinan926** [comment]
I thought #694 supports that?

**Comment by jkleckner** [comment]
I don't see anything in the documentation other than mounting it into the filesystem, not putting into the process environment.  Never having studied Go it is hard to decode what is really going on but I didn't see any references in the changed files to `envFrom` or `ConfigMap`.  How would it be used for that?

**Comment by liyinan926** [comment]
With the changes in #694, you can do the following:

```yaml
spec:
  driver:
    env:
      - name: env1
         valueFrom:
           configMapKeyRef:
             ...
      - name: env2
         valueFrom:
           secretKeyRef:
             ...
```

We need to update the documentation on this.
