### ISSUE TITLE
Lifecycle of Sidecar containers

### ISSUE THREAD

**Issue by ImpSy** [GoogleCloudPlatform/spark-on-k8s-operator#800]
Hello,

I'm currently having an issue using Sidecars:
I've created a Sidecar to tail `spark.eventLog` but the container never stop even when the driver is finished

My configuration as follow:
```
sparkConf:
  spark.eventLog.enabled: "true"
driver:
  volumeMounts:
  - name: event-log
    mountPath: "/tmp/spark-events"
  sidecars:
  - name: event-log-collector
    image: busybox
    args:
    - "/bin/sh"
    - "-c"
    - "sleep 30 && tail -f /tmp/spark-events/*.inprogress"
    volumeMounts:
    - name: event-log
      mountPath: "/tmp/spark-events"
volumes:
- name: event-log
  emptyDir: {}
```

Is this a bug or just not implemented ?
If that's the case, do you know any trick to stop the sidecar ?

Thanks in advance for your response 😃
