### ISSUE TITLE
the cpu limits in exec pod 

### ISSUE THREAD

**Issue by tingweiwu** [GoogleCloudPlatform/spark-on-k8s-operator#810]
I run the pi test `spark-py-pi.yaml`

```
kubectl get pods -n system
NAME                READY   STATUS    RESTARTS   AGE
pyspark-pi-driver   1/1     Running   0          2m57s
```
and get the error from the driver as the `Resource Quotas` have been setted in namespace `system`
```
20/02/13 12:15:10 ERROR Utils: Uncaught exception in thread kubernetes-executor-snapshots-subscribers-1
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://kubernetes.default.svc/api/v1/namespaces/system/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "pyspark-pi-1581596092621-exec-1" is forbidden: failed quota: system-resourcequota: must specify limits.cpu.

```
I have check the `pyspark-pi-driver ` and `pyspark-pi-1581596745205-exec-1` pod spec where I deploy the pi test `spark-py-pi.yaml` in default namespace 
pyspark-pi-driver
```
    resources:
      limits:
        cpu: 1200m
        memory: 896Mi
      requests:
        cpu: "1"
        memory: 896Mi
```

pyspark-pi-1581596745205-exec-1
```
    resources:
      limits:
        memory: 896Mi
      requests:
        cpu: "1"
        memory: 896Mi
```

so. the exec pod don't set cpu limits? how to solve this when the `Resource Quotas` have been setted in namespace

**Comment by tingweiwu** [comment]
soveld by  change the yaml to
```
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 2.4.4
    serviceAccount: spark
  executor:
    cores: 1
    coreLimit: "1200m"
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.4

```
