### ISSUE TITLE
memory value of driver or  exec pod is not the same as sparkapplication yaml

### ISSUE THREAD

**Issue by tingweiwu** [GoogleCloudPlatform/spark-on-k8s-operator#817]
when I apply a sparkapplicaiton. the cpu/memory  as the following
```
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
  executor:
    cores: 1
    coreLimit: "1200m"
    instances: 2
    memory: "512m"
```

and I find the actual memory value of driver or exec pod is `896Mi`
```
    resources:
      limits:
        cpu: 1200m
        memory: 896Mi
      requests:
        cpu: "1"
        memory: 896Mi
```
what's the reason for this switch
