### ISSUE TITLE
A little bit of confusion about `sparkVersion` in spec

### ISSUE THREAD

**Issue by tingweiwu** [GoogleCloudPlatform/spark-on-k8s-operator#823]
the api.doc describe this field
```
 SparkVersion is the version of Spark the application uses.
```
when I deploy the sprak-operator with `gcr.io/spark-operator/spark-operator:v2.4.5-v1beta2-latest`

I have tested both `sparkVersion: "2.4.5" ` and  `sparkVersion: "2.4.4" `  with `  image: "gcr.io/spark-operator/spark-py:v2.4.4"` in the following spec run successfully 
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-pi
  namespace: default
spec:
  type: Python
  pythonVersion: "2"
  mode: cluster
  image: "gcr.io/spark-operator/spark-py:v2.4.4"
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  sparkVersion: "2.4.4"
  ........
```
so how to set the right value of sparkVersion?
