### ISSUE TITLE
Duplicate value: "spark-local-dir-1"

### ISSUE THREAD

**Issue by alexakr** [GoogleCloudPlatform/spark-on-k8s-operator#828]
In version `v1beta2-1.1.0-2.4.5`, using volume "`spark-local-dir-1`" for Scratch Space causing the following error:
`KubernetesClientException: Failure executing: POST at: https://10.96.0.1/api/v1/namespaces/***/pods. Message: Pod "test-driver" is invalid: spec.volumes[4].name: Duplicate value: "spark-local-dir-1". Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.volumes[4].name, message=Duplicate value: "spark-local-dir-1", reason=FieldValueDuplicate, additionalProperties={})], group=null, kind=Pod, name=test-driver, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Pod "test-driver" is invalid: spec.volumes[4].name: Duplicate value: "spark-local-dir-1", metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={})`

**Comment by liyinan926** [comment]
Can you show your `SparkApplication` spec here?

**Comment by alexakr** [comment]
```
spec:
  sparkVersion: "2.4.5"
  type: Java
  mode: cluster
  image: "***"
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/app/demo.jar"
  mainClass: demo.DemoApp
  volumes:
    - name: configuration-volume
      emptyDir: {}
    - name: demo-volume
      persistentVolumeClaim:
        claimName: "demo-pvc"
    - name: history-server-volume
      persistentVolumeClaim:
        claimName: "spark-history-server-pvc"
    - name: "spark-local-dir-1"
      persistentVolumeClaim:
        claimName: "demo-pvc1"
    - name: "spark-local-dir-2"
      persistentVolumeClaim:
        claimName: "demo-pvc2"
    - name: "spark-local-dir-3"
      persistentVolumeClaim:
        claimName: "demo-pvc3"
  sparkConfigMap: spark-log4j-configmap
  sparkConf:
    "spark.eventLog.enabled": "true"
    "spark.eventLog.dir": "file:/mnt/history"
  driver:
    cores: 1
    coreLimit: "1000m"
    memory: "10G"
    labels:
      version: "2.4.5"
    serviceAccount: "spark"
    secrets:
      - name: cassandra
        path: /mnt/cassandra
        secretType: Generic
    envSecretKeyRefs:
      SPRING_DATA_CASSANDRA_USERNAME:
        name: cassandra
        key: user
      SPRING_DATA_CASSANDRA_PASSWORD:
        name: cassandra
        key: password
    volumeMounts:
      - name: configuration-volume
        mountPath: /opt/demo/config
      - name: demo-volume
        mountPath: /mnt/storage
      - name: history-server-volume
        mountPath: /mnt/history
    initContainers:
      - name: configuration-container
        image: "***"
        imagePullPolicy: Always
        volumeMounts:
          - name: configuration-volume
            mountPath: /opt/demo/config
  executor:
    cores: 2
    instances: 2
    memory: "2G"
    labels:
      version: "2.4.5"
    secrets:
      - name: cassandra
        path: /mnt/cassandra
        secretType: Generic
    envSecretKeyRefs:
      SPRING_DATA_CASSANDRA_USERNAME:
        name: cassandra
        key: user
    volumeMounts:
      - name: demo-volume
        mountPath: /mnt/storage
      - name: history-server-volume
        mountPath: /mnt/history
      - name: "spark-local-dir-1"
        mountPath: "/mnt/local1"
      - name: "spark-local-dir-2"
        mountPath: "/mnt/local2"
      - name: "spark-local-dir-3"
        mountPath: "/mnt/local3"
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/opt/spark/jars/jmx_prometheus_javaagent.jar"
      port: 9090
```
