### ISSUE TITLE
Support for separate node label selectors for driver and executors

### ISSUE THREAD

**Issue by devaraj-kavali** [GoogleCloudPlatform/spark-on-k8s-operator#890]
We are trying to launch the Driver in a specific node and Executors in different set of nodes, but the Apache spark provides common configuration spark.kubernetes.node.selector.[labelKey] for  both Driver and Executors.

There was discussion about adding separate node selectors in https://issues.apache.org/jira/browse/SPARK-25220 and https://github.com/apache/spark/pull/22212, and concluded that the same can be achieved with pod templates (https://issues.apache.org/jira/browse/SPARK-24434).

Can we add the support for this with spark-on-k8s-operator or is there a way to achieve the same?

**Comment by ringtail** [comment]
> We are trying to launch the Driver in a specific node and Executors in different set of nodes, but the Apache spark provides common configuration spark.kubernetes.node.selector.[labelKey] for both Driver and Executors.
> 
> There was discussion about adding separate node selectors in https://issues.apache.org/jira/browse/SPARK-25220 and [apache/spark#22212](https://github.com/apache/spark/pull/22212), and concluded that the same can be achieved with pod templates (https://issues.apache.org/jira/browse/SPARK-24434).
> 
> Can we add the support for this with spark-on-k8s-operator or is there a way to achieve the same?

We have supported this feature with webhook in spark operator.

**Comment by liyinan926** [comment]
You can use `nodeSelector` for both the driver and executor pods, e.g.,:

```yaml
spec:
  driver:
    nodeSelector:
      - key1: value1
      - key2: value2
  executor:
    nodeSelector:
      - key1: value1
      - key2: value2
```

**Comment by jkleckner** [comment]
It works quite well.  I use this to put the executors into a "scale to zero" resizable node pool by adding this to that section:
```
  executor:
    ...
    memory:    25000m
    labels:
      version: 2.4.5
      spark-executor: "true"
    nodeSelector:
      spark-executor-large: "true"
    tolerations:
    - key: "spark-executor"
      operator: Equal
      value: "true"
      effect: NoSchedule
```
