### ISSUE TITLE
envFrom doesn't always work

### ISSUE THREAD

**Issue by andizzle** [GoogleCloudPlatform/spark-on-k8s-operator#892]
I noticed that the envFrom does not always mount the env vars from configMap. After restart the driver pod a few times the env env vars would eventually be available.

In the SparkApplication:
```yaml
    Core Limit:                      1
    Cores:                           1
    Env From:
      Config Map Ref:
        Name:   flight-allocator
```

In pod description:
```yaml
    Requests:
      cpu:     1
      memory:  9011Mi
    Environment:
      SPARK_DRIVER_BIND_ADDRESS:   (v1:status.podIP)
      SPARK_LOCAL_DIRS:           /var/data/spark-cafb50ce-38ab-42e0-a674-02825d7322c5
      SPARK_CONF_DIR:             /opt/spark/conf
    Mounts:
      /opt/spark/conf from spark-conf-volume (rw)
      /var/data/spark-36de5f42-f08e-4f83-9a4d-2bf6b6de055e from spark-local-dir-1 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from spark-token-gkj8d (ro)
```

When the env var eventually gets mounted
```yaml
    Requests:
      cpu:     1
      memory:  9011Mi
    Environment Variables from:
      flight-allocator  ConfigMap  Optional: false
    Environment:
      SPARK_DRIVER_BIND_ADDRESS:   (v1:status.podIP)
      SPARK_LOCAL_DIRS:           /var/data/spark-79fca490-8bfe-45fc-875b-74cb0e5cfeec
      SPARK_CONF_DIR:             /opt/spark/conf
      SPARK_CONF_DIR:             /etc/spark/conf
    Mounts:
      /etc/spark/conf from spark-configmap-volume (ro)
      /opt/spark/conf from spark-conf-volume (rw)
      /var/data/spark-79fca490-8bfe-45fc-875b-74cb0e5cfeec from spark-local-dir-1 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from spark-token-gkj8d (ro)
```

I'm using `gcr.io/spark-operator/spark-operator:v1beta2-1.1.1-2.4.5`
