### ISSUE TITLE
How to pass the env variable SPARK_CLASSPATH to the pod?

### ISSUE THREAD

**Issue by yliu120** [GoogleCloudPlatform/spark-on-k8s-operator#893]
Hey,

I am running into issues that I can't define SPARK_CLASSPATH from the yaml file and pass it to the pod. I tried:

```
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 2.4.5
    envs:
      - name: SPARK_CLASSPATH
        value: "/docker/*"
```

Howeve, this is not actually working,

+ SPARK_CLASSPATH=':/opt/spark/jars/*'
+ env

I didn't see any change when entrypoint.sh get run.
