### ISSUE TITLE
Initial job has not accepted any resources

### ISSUE THREAD

**Issue by yliu120** [GoogleCloudPlatform/spark-on-k8s-operator#895]
Hi,

I successfully ran spark-operator on minikube with the SparkPi example. However, when I ran my own Spark application. I hit a very weird executor scheduling issue. Here is the log message:

```
20/04/30 04:59:49 INFO ExecutorPodsAllocator: Going to request 1 executors from Kubernetes.
20/04/30 04:59:49 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 7079.
20/04/30 04:59:49 INFO NettyBlockTransferService: Server created on spark-example-test-1588222781011-driver-svc.default.svc:7079
20/04/30 04:59:49 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
20/04/30 04:59:49 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, spark-example-test-1588222781011-driver-svc.default.svc, 7079, None)
20/04/30 04:59:49 INFO BlockManagerMasterEndpoint: Registering block manager spark-example-test-1588222781011-driver-svc.default.svc:7079 with 117.0 MB RAM, BlockManagerId(driver, spark-example-test-1588222781011-driver-svc.default.svc, 7079, None)
20/04/30 04:59:49 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, spark-example-test-1588222781011-driver-svc.default.svc, 7079, None)
20/04/30 04:59:49 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, spark-example-test-1588222781011-driver-svc.default.svc, 7079, None)
20/04/30 04:59:49 INFO ContextHandler: Started o.s.j.s.ServletContextHandler@552ed807{/metrics/json,null,AVAILABLE,@Spark}
20/04/30 05:00:19 INFO KubernetesClusterSchedulerBackend: SchedulerBackend is ready for scheduling beginning after waiting maxRegisteredResourcesWaitingTime: 30000(ms)
20/04/30 05:00:22 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('file:/opt/spark/work-dir/spark-warehouse').
20/04/30 05:00:22 INFO SharedState: Warehouse path is 'file:/opt/spark/work-dir/spark-warehouse'.
20/04/30 05:00:22 INFO ContextHandler: Started o.s.j.s.ServletContextHandler@58feb6b0{/SQL,null,AVAILABLE,@Spark}
20/04/30 05:00:22 INFO ContextHandler: Started o.s.j.s.ServletContextHandler@66d25ba9{/SQL/json,null,AVAILABLE,@Spark}
20/04/30 05:00:22 INFO ContextHandler: Started o.s.j.s.ServletContextHandler@7e3236d{/SQL/execution,null,AVAILABLE,@Spark}
20/04/30 05:00:22 INFO ContextHandler: Started o.s.j.s.ServletContextHandler@38a4e2b0{/SQL/execution/json,null,AVAILABLE,@Spark}
20/04/30 05:00:22 INFO ContextHandler: Started o.s.j.s.ServletContextHandler@7fe8c7db{/static/sql,null,AVAILABLE,@Spark}
20/04/30 05:00:23 INFO StateStoreCoordinatorRef: Registered StateStoreCoordinator endpoint
20/04/30 05:00:24 INFO ParquetFileFormat: Using default output committer for Parquet: org.apache.parquet.hadoop.ParquetOutputCommitter
20/04/30 05:00:24 INFO SQLHadoopMapReduceCommitProtocol: Using user defined output committer class org.apache.parquet.hadoop.ParquetOutputCommitter
20/04/30 05:00:24 INFO SQLHadoopMapReduceCommitProtocol: Using output committer class org.apache.parquet.hadoop.ParquetOutputCommitter
20/04/30 05:00:24 INFO SparkContext: Starting job: parquet at SparkMain.java:306
20/04/30 05:00:24 INFO DAGScheduler: Registering RDD 9 (keyBy at SparkMain.java:291) as input to shuffle 0
20/04/30 05:00:24 INFO DAGScheduler: Got job 0 (parquet at SparkMain.java:306) with 2 output partitions
20/04/30 05:00:24 INFO DAGScheduler: Final stage: ResultStage 1 (parquet at SparkMain.java:306)
20/04/30 05:00:24 INFO DAGScheduler: Parents of final stage: List(ShuffleMapStage 0)
20/04/30 05:00:24 INFO DAGScheduler: Missing parents: List(ShuffleMapStage 0)
20/04/30 05:00:24 INFO DAGScheduler: Submitting ShuffleMapStage 0 (MapPartitionsRDD[9] at keyBy at SparkMain.java:291), which has no missing parents
20/04/30 05:00:24 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 9.2 KB, free 117.0 MB)
20/04/30 05:00:24 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 4.1 KB, free 116.9 MB)
20/04/30 05:00:24 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on spark-example-test-1588222781011-driver-svc.default.svc:7079 (size: 4.1 KB, free: 117.0 MB)
20/04/30 05:00:24 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1163
20/04/30 05:00:24 INFO DAGScheduler: Submitting 2 missing tasks from ShuffleMapStage 0 (MapPartitionsRDD[9] at keyBy at SparkMain.java:291) (first 15 tasks are for partitions Vector(0, 1))
20/04/30 05:00:24 INFO TaskSchedulerImpl: Adding task set 0.0 with 2 tasks
20/04/30 05:00:39 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
20/04/30 05:00:54 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
20/04/30 05:01:09 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
20/04/30 05:01:24 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
20/04/30 05:01:39 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
20/04/30 05:01:54 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
20/04/30 05:02:09 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
20/04/30 05:02:24 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
20/04/30 05:02:39 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
20/04/30 05:02:54 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
20/04/30 05:03:09 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
```

It seems that the Kubernetes API server is not reachable for creating executor pods. I am sure that the resource of the minkube is sufficient. There is no clue to debug what's going wrong.

Could anybody give any clue on this?

**Comment by jkleckner** [comment]
The whole area of how Spark and k8s interact with resources is surprisingly complicated.
It probably deserves a whole tutorial.  And although `coreRequest` *is* documented in the api.doc it is not written about in the user guide.

Try playing with spec of the form below customized to your own problem.
It ensures that each pod is only asking for one core but is allowed to use more, 10 in this case.

```
  driver:
    cores: 1
    coreRequest: "1"
    memory: 512m
    ...
  sparkConf:
   spark.task.cpus: "1"
   spark.executor.cores: "10"
  executor:
    instances: 1     # Number of pods
    coreRequest: "1"
    memory:    25000m
```

Other useful resource:
https://blog.cloudera.com/how-to-tune-your-apache-spark-jobs-part-2/

**Comment by yliu120** [comment]
Thanks for the lint. Let me try it.

Yes. It is generally hard to understand how resources are negotiated between spark and Kubernetes. My current configuration is the following:

```
sparkVersion: "2.4.5"
  restartPolicy:
    type: Never
  volumes:
    - name: "tmp-volume"
      hostPath:
        path: "/tmp"
        type: Directory
    - name: "output-volume"
      hostPath:
        path: "/var/data/output"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 2.4.5
    serviceAccount: spark
    volumeMounts:
      - name: "tmp-volume"
        mountPath: "/tmp"
      - name: "output-volume"
        mountPath: "/output"
  executor:
    cores: 1
    instances: 1
    memory: "1g"
    labels:
      version: 2.4.5
    volumeMounts:
      - name: "tmp-volume"
        mountPath: "/tmp"
      - name: "output-volume"
        mountPath: "/output"
```

I will add what you recommend and try again.
