### ISSUE TITLE
Spark Operator Error 

### ISSUE THREAD

**Issue by samarthkansal** [GoogleCloudPlatform/spark-on-k8s-operator#906]
I am facing this issue while trying to run the spark operator on the kubernetes:
**_Error:_**
    `spark operator error : error: unable to recognize "spark-py.yaml": no matches for kind 
    "SparkApplication" in version "sparkapplications.sparkoperator.k8s.io/v1beta2"`

Configurations and the steps i performed:
- Installed helm2 
- Installed Tiller
- Created tiller account and provided Tiller with admin-cluster role
     - kubectl -n kube-system create serviceaccount tiller
     - kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube  - 
       system:tiller
- I can see this 
 ```
 - -bash-4.2$ kubectl get pods --namespace kube-system
NAME                               READY   STATUS    RESTARTS   AGE
coredns-66bff467f8-m4g2n           1/1     Running   0          5m42s
coredns-66bff467f8-xbfqq           1/1     Running   0          5m42s
etcd-minikube                      1/1     Running   0          5m52s
kindnet-phkb2                      1/1     Running   0          5m42s
kube-apiserver-minikube            1/1     Running   0          5m52s
kube-controller-manager-minikube   1/1     Running   0          5m52s
kube-proxy-rnc4g                   1/1     Running   0          5m42s
kube-scheduler-minikube            1/1     Running   0          5m52s
storage-provisioner                1/1     Running   0          5m56s
tiller-deploy-66fccb9847-2hm8h     1/1     Running   0          17s
```

- installed the SparkOperator

`**_$bash: helm install incubator/sparkoperator --namespace default --set operatorVersion=latest_**
````
NAME:   your-unicorn
LAST DEPLOYED: Fri May  8 13:41:33 2020
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ClusterRole
NAME                           CREATED AT
your-unicorn-sparkoperator-cr  2020-05-08T20:41:33Z

==> v1/ClusterRoleBinding
NAME                            ROLE                                       AGE
your-unicorn-sparkoperator-crb  ClusterRole/your-unicorn-sparkoperator-cr  1s

==> v1/Deployment
NAME                        READY  UP-TO-DATE  AVAILABLE  AGE
your-unicorn-sparkoperator  0/1    1           0          1s

==> v1/Pod(related)
NAME                                         READY  STATUS             RESTARTS  AGE
your-unicorn-sparkoperator-6c659fbffc-f5p5f  0/1    ContainerCreating  0         1s

==> v1/ServiceAccount
NAME                        SECRETS  AGE
your-unicorn-spark          1        0s
your-unicorn-sparkoperator  1        1s

==> v1beta1/CustomResourceDefinition
NAME                                             CREATED AT
scheduledsparkapplications.sparkoperator.k8s.io  2020-05-08T20:41:33Z
sparkapplications.sparkoperator.k8s.io           2020-05-08T20:41:33Z

```
- Checked API version:

$bash:  describe crd scheduledsparkapplications.sparkoperator.k8s.io | grep API Version

API Version:  apiextensions.k8s.io/v1
    API Version:  apiextensions.k8s.io/v1beta1
    API Version:  apiextensions.k8s.io/v1
          API Version:
                                          API Version:
                                          API Version:

- and the last step :
```
-bash-4.2$ kubectl apply -f spark-py.yaml
error: unable to recognize "spark-py.yaml": no matches for kind "SparkApplication" in version "sparkapplications.sparkoperator.k8s.io/v1beta2"




```

**Comment by samarthkansal** [comment]
_**- My manifest file**_

```
apiVersion: sparkoperator.k8s.io/v1beta1     (Tried with beta 2, did not work)
kind: SparkApplication
metadata:
  name: spark-py
  namespace: default
spec:
  type: Python
  mode: cluster
  image: "spark-py:v3.0"
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/spark/examples/src/main/python/spark-submit-old.py"
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never
  driver:
    cores: 0.1
    coreLimit: "200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: spark-sa
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.0.0
```
