### ISSUE TITLE
[FATAL tini (16)] exec driver-py failed: No such file or directory

### ISSUE THREAD

**Issue by samarthkansal** [GoogleCloudPlatform/spark-on-k8s-operator#908]
I have been trying to submit a spark job using spark operator on K8. I have done the setup using helm and installed spark operator which sucessfully submits the spark job but after that driver pod exists with the error : 

`[FATAL tini (16)] exec driver-py failed: No such file or directory`

```
- log of my pod:
   Driver:
    Cores:  1
    Labels:
      Version:        3.0.0
    Memory:           900m
    Service Account:  spark
  Executor:
    Cores:      5
    Instances:  3
    Labels:
      Version:            3.0.0
    Memory:               5000m
  Image:                  spark-py:v3.0
  Image Pull Policy:      Never
  Main Application File:  local:///opt/spark/examples/src/main/python/spark-submit-old.py
  Mode:                   cluster
  Python Version:         3
  Restart Policy:
    Type:         Never
  Spark Version:  3.0.0
  Type:           Python
Status:
  Application State:
    Error Message:  driver pod failed with ExitCode: 127, Reason: Error
    State:          FAILED
  Driver Info:
    Pod Name:                    spark-py-driver
    Web UI Address:              10.98.90.151:4040
    Web UI Port:                 4040
    Web UI Service Name:         spark-py-ui-svc
  Execution Attempts:            1
  Last Submission Attempt Time:  2020-05-10T21:21:03Z
  Spark Application Id:          spark-1389c026afbb49808c181e7f548e4720
  Submission Attempts:           1
  Submission ID:                 d84068d3-5372-4f5f-bae4-5a70f12a9129
  Termination Time:              2020-05-10T21:21:06Z
Events:
  Type     Reason                     Age   From            Message
  ----     ------                     ----  ----            -------
  Normal   SparkApplicationAdded      12s   spark-operator  SparkApplication spark-py was added, enqueuing it for submission
  Normal   SparkApplicationSubmitted  9s    spark-operator  SparkApplication spark-py was submitted successfully
  Warning  SparkDriverFailed          6s    spark-operator  Driver spark-py-driver failed
  Warning  SparkApplicationFailed     6s    spark-operator  SparkApplication spark-py failed: driver pod failed with ExitCode: 127, Reason: Error
-bash-4.2$ kubectl logs spark-py-driver
++ id -u
+ myuid=185
++ id -g
+ mygid=0
+ set +e
++ getent passwd 185
+ uidentry=
+ set -e
+ '[' -z '' ']'
+ '[' -w /etc/passwd ']'
+ echo '185:x:185:0:anonymous uid:/opt/spark:/bin/false'
+ SPARK_CLASSPATH=':/opt/spark/jars/*'
+ env
+ grep SPARK_JAVA_OPT_
+ sort -t_ -k4 -n
+ sed 's/[^=]*=\(.*\)/\1/g'
+ readarray -t SPARK_EXECUTOR_JAVA_OPTS
+ '[' -n '' ']'
+ '[' 3 == 2 ']'
+ '[' 3 == 3 ']'
++ python3 -V
+ pyv3='Python 3.7.3'
+ export PYTHON_VERSION=3.7.3
+ PYTHON_VERSION=3.7.3
+ export PYSPARK_PYTHON=python3
+ PYSPARK_PYTHON=python3
+ export PYSPARK_DRIVER_PYTHON=python3
+ PYSPARK_DRIVER_PYTHON=python3
+ '[' -n ']'
+ '[' -z ']'
++ /bin/hadoop classpath
/opt/entrypoint.sh: line 62: /bin/hadoop: No such file or directory
+ export SPARK_DIST_CLASSPATH=
+ SPARK_DIST_CLASSPATH=
+ '[' -z ']'
Non-spark-on-k8s command provided, proceeding in pass-through mode...
+ case "$1" in
+ echo 'Non-spark-on-k8s command provided, proceeding in pass-through mode...'
+ CMD=("$@")
+ exec /usr/bin/tini -s -- driver-py --properties-file /opt/spark/conf/spark.properties --class org.apache.spark.deploy.PythonRunner
[FATAL tini (16)] exec driver-py failed: No such file or directory
```

```
My manifest file:

apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-py
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "spark-py:v3.0"
  imagePullPolicy: Never
  mainApplicationFile: "local:///opt/spark/examples/src/main/python/spark-submit-old.py"
  sparkVersion: 3.0.0
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: 900m
    labels:
      version: 3.0.0
    serviceAccount: spark
  executor:
    cores: 5
    instances: 3
    memory: 5000m
    labels:
      version: 3.0.0
```
