### ISSUE TITLE
Pods continue to run after spark application fails or runs into exception

### ISSUE THREAD

**Issue by robbyki** [GoogleCloudPlatform/spark-on-k8s-operator#920]
How can I cause my pods and execturos to immediately fail when spark application fails or reaches an exception. Right now, I have a workaround where we force a non-zero exit inside a try-catch but I'm thinking there is a more graceful way to send a kill signal to the pods. 

*What I have tried:*
`terminationGracePeriodSeconds: 0` still does not cause driver and executors from pod to terminate
Prestop hook as follows also did not terminate anything despite exception from app reached:
```
      preStop:
        exec:
          command:
          - /bin/bash
          - -c
          - touch /var/run/killspark && sleep 65
```
