### ISSUE TITLE
CRDs don't pass validation on k8s 1.18

### ISSUE THREAD

**Issue by ddobrijalowski** [GoogleCloudPlatform/spark-on-k8s-operator#921]
As a result of: https://github.com/kubernetes/kubernetes/pull/88076 that is included in k8s 1.18 (https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#other-api-changes) keys have to be either required or have a default value.

I've tried this on v1beta2-1.1.1-2.4.5 and master.

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:30:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

```
# kubectl apply -f sparkoperator.k8s.io_sparkapplications.yaml
The CustomResourceDefinition "sparkapplications.sparkoperator.k8s.io" is invalid: 
* spec.validation.openAPIV3Schema.properties[spec].properties[executor].properties[sidecars].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
* spec.validation.openAPIV3Schema.properties[spec].properties[executor].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
* spec.validation.openAPIV3Schema.properties[spec].properties[driver].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
* spec.validation.openAPIV3Schema.properties[spec].properties[driver].properties[sidecars].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
```

```
# kubectl apply -f sparkoperator.k8s.io_scheduledsparkapplications.yaml 
The CustomResourceDefinition "scheduledsparkapplications.sparkoperator.k8s.io" is invalid: 
* spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[driver].properties[sidecars].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
* spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[driver].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
* spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[executor].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
* spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[executor].properties[sidecars].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
```

Default values were introduced with apiextensions.k8s.io/v1, so without migrating to it the only option is to add protocol as a required field.

Workaround using kustomize:
* kustomization.yaml 
```
resources:
- spark-operator-with-webhook.yaml
- spark-operator-rbac.yaml
- crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml
- crds/sparkoperator.k8s.io_sparkapplications.yaml
patchesStrategicMerge:
- patches/scheduledsparkapplications.yaml
- patches/sparkapplications.yaml
```

* patches/scheduledsparkapplications.yaml 
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: scheduledsparkapplications.sparkoperator.k8s.io
spec:
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            template:
              properties:
                driver:
                  properties:
                    sidecars:
                      items:
                        properties:
                          ports:
                            items:
                              required:
                              - containerPort
                              - protocol
                    initContainers:
                      items:
                        properties:
                          ports:
                            items:
                              required:
                              - containerPort
                              - protocol
                executor:
                  properties:
                    sidecars:
                      items:
                        properties:
                          ports:
                            items:
                              required:
                              - containerPort
                              - protocol
                    initContainers:
                      items:
                        properties:
                          ports:
                            items:
                              required:
                              - containerPort
                              - protocol
```

* patches/sparkapplications.yaml
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sparkapplications.sparkoperator.k8s.io
spec:
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            driver:
              properties:
                sidecars:
                  items:
                    properties:
                      ports:
                        items:
                          required:
                          - containerPort
                          - protocol
                initContainers:
                  items:
                    properties:
                      ports:
                        items:
                          required:
                          - containerPort
                          - protocol
            executor:
              properties:
                sidecars:
                  items:
                    properties:
                      ports:
                        items:
                          required:
                          - containerPort
                          - protocol
                initContainers:
                  items:
                    properties:
                      ports:
                        items:
                          required:
                          - containerPort
                          - protocol
```
