### ISSUE TITLE
containerPort is not added to driver and executor pods when specifying monitoring in app spec

### ISSUE THREAD

**Issue by AliGouta** [GoogleCloudPlatform/spark-on-k8s-operator#934]
Jmx exporter works well and it does export metrics **locally** that might be scrapped by prometheus. However, there is no `containerPort` added to the pods after starting the application so that Prometheus may scrap these metrics through a `Service/ServiceMonitor` for instance.

**To reproduce, add the following in the application spec:**

```
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/prometheus/jmx_prometheus_javaagent-0.12.0.jar"
      port: 9999
```

**On executor pods, the exposed ports are:**

```
    name: executor
    ports:
    - containerPort: 7079
      name: blockmanager
      protocol: TCP
    resources:
```

**On Driver pod, the exposed ports are:**

```
    name: spark-kubernetes-driver
    ports:
    - containerPort: 7078
      name: driver-rpc-port
      protocol: TCP
    - containerPort: 7079
      name: blockmanager
      protocol: TCP
    - containerPort: 4040
      name: spark-ui
      protocol: TCP
    resources:
```

**Exepected behaviour is to add the prometheus exporter port to the pod as a containerPort:**

```
    name: spark-kubernetes-driver
    ports:
    ....
    - containerPort: 9999
      protocol: TCP
    resources:
```

A workaround would be to add a sidecar container. But this is not proper.

A PR is on the way to fix this (already tested) :).

**Comment by liyinan926** [comment]
Related: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/476, https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/825.

**Comment by krish512** [comment]
Did something get changed? I still don't see the prometheus port getting creating even after passing the prometheus options to SparkApplication,
```
monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: /opt/spark/jars/jmx_prometheus_javaagent-0.15.0.jar
      port: 8090
```

I've ensured my jar file is present in /opt/spark/jars/jmx_prometheus_javaagent-0.15.0.jar location
