### ISSUE TITLE
ImagePullBackOff on using operatorVersion

### ISSUE THREAD

**Issue by scottydelta** [GoogleCloudPlatform/spark-on-k8s-operator#951]
The pod fails with `ImagePullBackOff` upon using `--set operatorVersion=latest` while installing the spark-operator from `http://storage.googleapis.com/kubernetes-charts-incubator` repo. 

I want to use `imagePullSecrets` to pull image from Gitlab registry which I believe can only be done on latest version?

thanks

**Comment by liyinan926** [comment]
Can you try `--set operatorVersion=v2.4.5-v1beta2-latest`?

**Comment by scottydelta** [comment]
The operator runs now but the spark deployment fails with this log:

`Error from server (BadRequest): container "spark-kubernetes-driver" in pod "pyspark-pi-driver" is waiting to start: trying and failing to pull image`

This is my deployment yaml:

```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-pi
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "registry.gitlab.com/user/repo/spark/spark-py:latest"
  imagePullSecrets:
  - docker-registry-secret
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  sparkVersion: "2.4.5"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 2.4.5
    serviceAccount: spark
  executor:
    cores: 1
    instances: 3
    memory: "512m"
    labels:
      version: 2.4.5
```

Kubernetes Version: `v1.15.12`
operatorVersion: `v2.4.5-v1beta2-latest`
