### ISSUE TITLE
Spark 2.4.6 does not work with operator

### ISSUE THREAD

**Issue by AceHack** [GoogleCloudPlatform/spark-on-k8s-operator#965]
I will try and get further details and see if I can find a spark code changes that causes this problem but memory and cpu limits do not work correctly with spark 2.4.6 and cause sparkapps to never start.

`From sparkapp.yaml`
```
  driver:
    cores: 1
    coreLimit: 2000m
    memory: 512m
    memoryOverhead: 512m
  executor:
    cores: 1
    coreLimit: 2000m
    memory: 512m
    memoryOverhead: 512m
```

`From actual driver pod when using Spark 2.4.6`
```
  resources:
    limits:
      cpu: 2k
      memory: 1024
    requests:
      cpu: 1
      memory: 1024
```
This breaks everything and the container never gets created

`From actual driver pod when using Spark 2.4.5`
```
  resources:
    limits:
      cpu: 2000m
      memory: 1024m
    requests:
      cpu: 1
      memory: 1024m
```
This works
