### ISSUE TITLE
Gang-scheduling with Volcano version=latest and version=v0.4 does not work with spark-operator

### ISSUE THREAD

**Issue by Gouthamkreddy1234** [GoogleCloudPlatform/spark-on-k8s-operator#968]
**Spark-operator setup with helm**-
helm install incubator/sparkoperator --namespace spark-operator --set enableBatchScheduler=true --set enableWebhook=true

**Volcano installation** -
volcano version v0.4/latest - [https://github.com/volcano-sh/volcano/blob/release-0.4/installer/volcano-development.yaml](https://github.com/volcano-sh/volcano/blob/release-0.4/installer/volcano-development.yaml) (Changed all the image versions from :latest to :v0.4 and tried too)

**K8s version**: 1.14 

Two unrelated podgroup created after the Sparkapplication object is created. These podgroups do not match with the Sparkapplication's name and do not contain the minResources as well.

Can someone give me a working combination of helm install (with chart, operatorimage and operator-version) and the correct version of volcano to use with this?

**Sparkapplication** - (20 executors do not fit in my cluster)
```
--
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-pi-delay-job
  namespace: default
spec:
  type: Python
  pythonVersion: "2"
  mode: cluster
  image: "gcr.io/spark-operator/spark-py:v2.4.4"
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  arguments: ["150"]
  sparkVersion: "2.4.0"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  batchScheduler: "volcano"
  driver:
    cores: 1
    memory: "512m"
    labels:
      version: 2.4.0
    serviceAccount: spark
  executor:
    cores: 3
    instances: 20
    memory: "512m"
    labels:
      version: 2.4.0
```

** kubectl get podgroup** - 
```
ubuntu@k8s-sample-cluster-goutham-master-0:~/spark-operator-volcano-demo/demos/pod-delay-creation$ kubectl get podgroups
NAME                                            AGE
podgroup-d0010724-c0ef-11ea-87a8-42010ab44860   35s
podgroup-d19b000a-c0ef-11ea-87a8-42010ab44860   26s
ubuntu@k8s-sample-cluster-goutham-master-0:~/spark-operator-volcano-demo/demos/pod-delay-creation$
```

**PodGroup1** -
```
ubuntu@k8s-sample-cluster-goutham-master-0:~/spark-operator-volcano-demo/demos/pod-delay-creation$ kubectl describe pg podgroup-d0010724-c0ef-11ea-87a8-42010ab44860
Name:         podgroup-d0010724-c0ef-11ea-87a8-42010ab44860
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  scheduling.volcano.sh/v1beta1
Kind:         PodGroup
Metadata:
  Creation Timestamp:  2020-07-08T07:51:23Z
  Generation:          155
  Owner References:
    API Version:     sparkoperator.k8s.io/v1beta2
    Controller:      true
    Kind:            SparkApplication
    Name:            pyspark-pi-delay-job
    UID:             d0010724-c0ef-11ea-87a8-42010ab44860
  Resource Version:  7417246
  Self Link:         /apis/scheduling.volcano.sh/v1beta1/namespaces/default/podgroups/podgroup-d0010724-c0ef-11ea-87a8-42010ab44860
  UID:               d19f77f3-c0ef-11ea-87a8-42010ab44860
Spec:
  Min Member:  1
Status:
  Failed:  1
  Phase:   Inqueue
Events:
  Type     Reason         Age                     From     Message
  ----     ------         ----                    ----     -------
  Normal   Scheduled      3m20s                   volcano  0/1 tasks in gang unschedulable: pod group is ready, 1 minAvailable, 0 Pending
  Warning  Unschedulable  2m10s (x24 over 2m33s)  volcano  0/1 tasks in gang unschedulable: pod group is not ready, 1 Failed, 1 minAvailable.
```

**PodGroup2**- (minResources not updated and SparkApplication still partially scheduled although full application does not fit in the cluster)
```
ubuntu@k8s-sample-cluster-goutham-master-0:~/spark-operator-volcano-demo/demos/pod-delay-creation$ kubectl describe podgroup podgroup-a8e5601e-c0f0-11ea-87a8-42010ab44860
Name:         podgroup-a8e5601e-c0f0-11ea-87a8-42010ab44860
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  scheduling.volcano.sh/v1beta1
Kind:         PodGroup
Metadata:
  Creation Timestamp:  2020-07-08T07:57:33Z
  Generation:          87
  Owner References:
    API Version:     v1
    Controller:      true
    Kind:            Pod
    Name:            pyspark-pi-delay-job-driver
    UID:             a8e5601e-c0f0-11ea-87a8-42010ab44860
  Resource Version:  7418428
  Self Link:         /apis/scheduling.volcano.sh/v1beta1/namespaces/default/podgroups/podgroup-a8e5601e-c0f0-11ea-87a8-42010ab44860
  UID:               ae3c339b-c0f0-11ea-87a8-42010ab44860
Spec:
  Min Member:  1
Status:
  Conditions:
    Last Transition Time:  2020-07-08T07:59:35Z
    Message:               1/0 tasks in gang unschedulable: pod group is not ready, 1 minAvailable.
    Reason:                NotEnoughResources
    Status:                True
    Transition ID:         05c4327d-2154-4207-ad4b-976c396ae1ad
    Type:                  Unschedulable
  Phase:                   Inqueue
Events:
  Type     Reason         Age                  From     Message
  ----     ------         ----                 ----     -------
  Normal   Scheduled      2m2s (x2 over 2m2s)  volcano  0/2 tasks in gang unschedulable: pod group is ready, 1 minAvailable, 0 Pending
  Normal   Scheduled      2m1s                 volcano  2/5 tasks in gang unschedulable: pod group is ready, 1 minAvailable, 2 Pending
  Warning  Unschedulable  61s (x22 over 82s)   volcano  0/0 tasks in gang unschedulable: pod group is not ready, 1 minAvailable.
```

**kubectl get pods** - 
```
ubuntu@k8s-sample-cluster-goutham-master-0:~/spark-operator-volcano-demo/demos/pod-delay-creation$ kubectl get pods
NAME                                        READY   STATUS    RESTARTS   AGE
pyspark-pi-delay-job-1594195043327-exec-1   1/1     Running   0          10s
pyspark-pi-delay-job-1594195043327-exec-2   1/1     Running   0          10s
pyspark-pi-delay-job-1594195043327-exec-3   1/1     Running   0          10s
pyspark-pi-delay-job-1594195043327-exec-4   0/1     Pending   0          10s
pyspark-pi-delay-job-1594195043327-exec-5   0/1     Pending   0          9s
pyspark-pi-delay-job-driver                 1/1     Running   0          19s
ubuntu@k8s-sample-cluster-goutham-master-0:~/spark-operator-volcano-demo/demos/pod-delay-creation$
```

@TommyLike Your demo combination of operator-image and volcano image works fine but my above helm command with volcano any volcano versions does not work - 

```
https://github.com/TommyLike/spark-operator-volcano-demo/blob/master/hack/volcano-0.2.yaml

helm install incubator/sparkoperator --namespace spark-operator --set enableBatchScheduler=true --version 0.3.1 --set operatorImageName=tommylike/spark-operator --set operatorVersion=0.0.5 --set enableWebhook=true
```

What is the right combination of helm install and volcano to use for this to work properly?
