### ISSUE TITLE
Specifying tnsnames

### ISSUE THREAD

**Issue by mmpereira** [GoogleCloudPlatform/spark-on-k8s-operator#977]
Hello,

I'm trying to read data from an Oracle database and for that I have to specify the location of the tnsnames.ora file. 
Before using the operator I would specify the path to the file through the _extraJavaOptions_ variable as such:
`time spark/bin/spark-submit --class "<classname>" --master "local[4]" --conf "spark.driver.extraJavaOptions=-Doracle.net.tns_admin=<path to .ora>" whatever.jar`

Now I have tried to specify the variable spec.driver.javaOptions with a path to the .ora. like this:
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: etl
  namespace: default
spec:
  type: Java
  mode: cluster
  image: <image>
  imagePullPolicy: Always
  imagePullSecrets: 
    - regcred
  mainClass: etl.example.BasicETL
  mainApplicationFile: "local:///opt/apps/etl.jar"
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never
  
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: spark
    javaOptions: "-Doracle.net.tns_admin=local:///opt/apps/"
    extraJavaOptions: "-Doracle.net.tns_admin=local:///opt/apps/"

  executor:
    cores: 4
    instances: 4
    memory: "512m"
    labels:
      version: 3.0.0
```
 I have checked the generated configmap and the variables are there correctly:

`    spark.driver.extraJavaOptions=-Doracle.net.tns_admin\=local\:///opt/apps/ `

It seems however the path to .ora is still not correct as the database identifier cannot be resolved:

```
Exception in thread "main" java.sql.SQLRecoverableException: IO Error: could not resolve the connect identifier  "<db name>"
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:774)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:688)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691)
	at org.apache.spark.sql.execution.datasources.jdbc.DriverWrapper.connect(DriverWrapper.scala:45)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$createConnectionFactory$1(JdbcUtils.scala:64)
```
Also in the logs there is the spark-submit command issued which seems to be missing the specified options:
`exec /usr/bin/tini -s -- /opt/spark/bin/spark-submit --conf spark.driver.bindAddress=10.100.233.161 --deploy-mode client --properties-file /opt/spark/conf/spark.properties --class etl.example.BasicETL spark-internal`

Any idea what I might be doing wrong?
